### ISSUE TITLE
sqlite3.OperationalError: duplicate column name: Value

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#101]
Trying to install the dataset [birchallchapacuran](https://github.com/lexibank/birchallchapacuran) into SQLite via `lexibank load birchallchapacuran`, and I get the following traceback:

```
Traceback (most recent call last):
  File "/Users/simon/files/Projects/lexibank2018/env/bin/lexibank", line 11, in <module>
    load_entry_point('pylexibank', 'console_scripts', 'lexibank')()
  File "/Users/simon/projects/lexibank2018/pylexibank/src/pylexibank/__main__.py", line 139, in main
    sys.exit(parser.main())
  File "/Users/simon/projects/lexibank2018/env/lib/python3.6/site-packages/clldutils-2.6.3-py3.6.egg/clldutils/clilib.py", line 110, in main
    catch_all=catch_all, parsed_args=args)
  File "/Users/simon/projects/lexibank2018/env/lib/python3.6/site-packages/clldutils-2.6.3-py3.6.egg/clldutils/clilib.py", line 82, in main
    self.commands[args.command](args)
  File "/Users/simon/projects/lexibank2018/env/lib/python3.6/site-packages/clldutils-2.6.3-py3.6.egg/clldutils/clilib.py", line 35, in __call__
    return self.func(args)
  File "/Users/simon/projects/lexibank2018/pylexibank/src/pylexibank/commands/misc.py", line 126, in load
    with_dataset(args, _load, default_to_all=True)
  File "/Users/simon/projects/lexibank2018/pylexibank/src/pylexibank/commands/util.py", line 28, in with_dataset
    func(get_dataset(args, dataset.id), **vars(args))
  File "/Users/simon/projects/lexibank2018/pylexibank/src/pylexibank/commands/util.py", line 37, in _load
    db.load(ds)
  File "/Users/simon/projects/lexibank2018/pylexibank/src/pylexibank/db.py", line 365, in load
    if self._create_table_if_not_exists(t):
  File "/Users/simon/projects/lexibank2018/pylexibank/src/pylexibank/db.py", line 345, in _create_table_if_not_exists
    conn.execute(table.sql)
sqlite3.OperationalError: duplicate column name: Value
```

..which appears to be because FormTable is getting two `Value` columns?

```
CREATE TABLE FormTable (
    `ID` TEXT,
    `Local_ID` TEXT,
    `Language_ID` TEXT,
    `Parameter_ID` TEXT,
    `Value` TEXT,
    `Form` TEXT,
    `Segments` TEXT,
    `Comment` TEXT,
    `Cognacy` TEXT,
    `Loan` INTEGER,
    `Value` TEXT,
    `dataset_ID` TEXT NOT NULL,
    PRIMARY KEY(`dataset_ID`, `ID`),
    FOREIGN KEY(`dataset_ID`) REFERENCES dataset(`ID`) ON DELETE CASCADE,
    FOREIGN KEY(`dataset_ID`,`Language_ID`) REFERENCES LanguageTable(`dataset_ID`,`ID`) ON DELETE CASCADE,
    FOREIGN KEY(`dataset_ID`,`Parameter_ID`) REFERENCES ParameterTable(`dataset_ID`,`ID`) ON DELETE CASCADE
)
```

**Comment by SimonGreenhill** [comment]
Also, does `verbose` get passed correctly here? I can't get it working?

**Comment by xrotwang** [comment]
Sounds like either your db is outdated or the dataset you try to load. At
some point, the Value column had the wrong propertyUrl and wasn't matched
properly with an existing column in the db.

Simon J Greenhill <notifications@github.com> schrieb am Di., 9. Juli 2019,
04:16:

**Comment by SimonGreenhill** [comment]
cldf validate passes?

**Comment by xrotwang** [comment]
Yes, for a Wordlist, only Form is required. So Value without propertyUrl
passes as non-standard column.

Simon J Greenhill <notifications@github.com> schrieb am Di., 9. Juli 2019,
06:58:

**Comment by LinguList** [comment]
the error does not replicate with me...

- **Varieties:** 10
- **Concepts:** 125
- **Lexemes:** 1,037
- **Synonymy:** 1.06
- **Cognacy:** 1,037 cognates in 285 cognate sets (98 singletons)
- **Cognate Diversity:** 0.18
- **Invalid lexemes:** 0
- **Tokens:** 5,481
- **Segments:** 39 (3 BIPA errors, 3 CTLS sound class errors, 36 CLTS modified)
- **Inventory size (avg):** 22.20

**Comment by xrotwang** [comment]
If you are starting out with an empty db, this error will never happen.

Johann-Mattis List <notifications@github.com> schrieb am Di., 9. Juli 2019,
07:02:

**Comment by SimonGreenhill** [comment]
Ok, so I've added Form as another field and that seems to fix it. So, let me get this clear --'Form' is the *raw* value in the dataset,  'Value' is a cleaned thing, and 'Segments' is the Segmented version of 'Value'  (i.e. Form -> Value -> Segments)

**Comment by xrotwang** [comment]
No, the other way round. Value is form-as-in-source, Form is what segments
are derived from.

Simon J Greenhill <notifications@github.com> schrieb am Di., 9. Juli 2019,
10:00:

**Comment by SimonGreenhill** [comment]
Ahh, ok, we should document this somewhere :)

**Comment by xrotwang** [comment]
I think I did in lexibank's README.

Simon J Greenhill <notifications@github.com> schrieb am Di., 9. Juli 2019,
10:03:
