### ISSUE TITLE
travis links in readme.md are missing

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#102]
e.g. https://github.com/lexibank/chenhmongmien/commit/add6de5d726b5bceab1b3e17f95fa86d7188c928

i.e. links to None

**Comment by xrotwang** [comment]
Including a travis badge when `Dataset.github_repo` is `None` is a `pylexibank` bug. But presumably, `github_repo` should have returned something useful.

**Comment by xrotwang** [comment]
The regex here https://github.com/lexibank/pylexibank/blob/96502588cf0d2378fe9678ffa0b1ed22fe51387a/src/pylexibank/dataset.py#L244 is too specific. Remote URLs may lack the `.git` suffix.
