### ISSUE TITLE
Show glottolog and concepticon versions rather than config.ini

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#105]
Calling lexibank spits this out:
```Using configuration file at:
/Users/simon/Library/Application Support/pylexibank/config.ini
```

... which is helpful, but not as helpful as displaying the glottolog/concepticon versions directly e.g.:

```Using:
glottolog:  v4.0 /path/to/glottolog
concepticon: v2.0 /path/to/concepticon
```

Actually, this would also be helpful to print when running makecldf too.

**Comment by xrotwang** [comment]
superseded with new catalog handling.
