### ISSUE TITLE
Lexibank check should raise error if concepts.tsv is in concepticon

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#108]
Many lexibank datasets have concepts.tsv in ./etc/ but these are also stored in concepticon. The problem is that if concepticon diverges/updates, the mapping in the lexibank datasets could become outdated/wrong. 

So, if there is a concept list in concepticon for a dataset, we should **not** have a concepts.tsv in ./etc/.

**Comment by xrotwang** [comment]
Such a check may be too coarse. I think we have datasets where some concepts in addition to the ones from a concepticon list are used. Maybe a warning would be appropriate - but ultimately it is the responsibility of the `makecldf` code of the dataset to make sure it is pulling the information from concepticon when appropriate.

**Comment by LinguList** [comment]
I just saw (forgot it) that we already show if a concepticon concept list is available: https://github.com/lexibank/beidasinitic (compare vs. https://github.com/lexibank/yanglalo). I guess what is important is just to make clearer (to us when reviewing the code) that NOT using a concepticon list should be the exception (and yanglalo, e.g., is in concepticon, I am currently revising it).

**Comment by SimonGreenhill** [comment]
Yes, a warning -- as this should be a rare situation to be avoided where possible.

**Comment by LinguList** [comment]
I have now updated quite a few of our major repositories, after my concepticon PR from yesterday. The question I am asking myself is: do we pin a specific concepticon version as well, or a minimal version, on a dataset's setup, or how can we account for that, as the data is now separated from the code?

**Comment by chrzyki** [comment]
I find this to be a difficult question. In my opinion, this is interconnected with the releases cycles of the two catalogues. Given the current, slower, release cycles, I think pinning specific versions is good and in my opinion should be preferred. If we want minimal versions, this should imo also lead two faster release cycles.

**Comment by SimonGreenhill** [comment]
Going for a minimal version for concepticon would match how we're handling glottolog, but I can see @chryki's point. There's no reason we can't speed up releases of concepticon though -- releasing it is is little effort, right? so any new list added could generate a new version.

**Comment by LinguList** [comment]
In fact, I just spent the last days adding conceptlists to concepticon that were only implicitly there before. This is a lot of effort, I'd say, as you need to follow all those guides we have. I think it should be done, and all responsible for their datasets should do it, but I would not like to have this as a full requirement. Specifically also when you think about things that are in flux, or cases of datastes that are not yet published or whatever.

**Comment by xrotwang** [comment]
Maybe we could adopt some sort of "fast-track" releases of Concepticon, i.e. each new list increments the patch version. But I'd be hesitant to change the concept sets within patch versions.

**Comment by xrotwang** [comment]
@SimonGreenhill I understand that getting stuff into Concepticon (and Glottolog) properly is a bottleneck for fast turn-around of lexibank datasets. But I think there's a (good) reason for this. These are issues where a dataset creator must coordinate with the rest of the community, and that shouldn't happen too quickly.

We always have the git commit hashes, so maybe we'd rather need a more formalized WIP status for datasets, which are compiled against unreleased versions of Concepticon of Glottolog.

**Comment by LinguList** [comment]
So for our very case, I started tagging the lists in github, for their properties. That was more for me to see what is going on there, as I know the tags are not necessarily operable computationally. Anyway, so far I see the following characteristics for consistent enhancement:

1. conceptlist in concepticon: `Dataset().metadata.conceptlist` gives you the answer, so for a collection, one can just check that, and it's on our README.md
2. I tagged well-segmented datasets with `clts` now (see [here](https://github.com/search?q=topic%3Aclts+org%3Alexibank&type=Repositories), these have no errors in bipa, or only one. Every maintainer of a dataset should see if they can add an orthoprofile, as sometimes, we could still do that, but it has not been done.
3. The metadata should be fine, i.e., a good title for a repo, not just the identifier, and a useful reference, not inconsistent pasting. 
4. The sources should also follow standards, i.e., avoiding misc, if it's a book, and if it's a book, not only publisher, but also address, etc.
5. If possible, and if provided, morphological segmentation should be maintained (not always done so far).

I guess this is some basic checklist. Ideally, it would be easy to `grep` all repositories that are fine with respect to conceptlist, clts, and morphemes, but maybe for the time being, it's enough if one makes list for oneself? What I experience now, however, is that I cannot easily maintain the data, as I always need to check which dataset is in clics, which is not, which one did I forget, etc.

**Comment by SimonGreenhill** [comment]
can this just solved by better checking and error messages? i.e. makecldf complains if there's a concepts.tsv in lexibank AND in concepticon-data? This would allow people to work on datasets before submitting them to concepticon (using concepts.tsv) and when the list is moved into concepticon it'll generate a warning. To allow lexibank to have different mappings the warning could just be generated if the two lists are *different*.

**Comment by SimonGreenhill** [comment]
@LinguList -- what about making a wiki page in lexibank/lexibank where we list our repositories, and have a series of columns for all those things you mention. Tick them if it's done (this will help us get things best for 1.0)

**Comment by LinguList** [comment]
In fact, quite a few things seem to be best handled by the one whos doing the code being aware of things. E.g. the code with concepticon-conceptlist and with concepts.tsv is quite different. So you actively re-write, and it seems, a warning would not even be needed then.

**Comment by LinguList** [comment]
I like the wiki idea. I understand @xrotwang would prefer to just extract these things from zenodo or similar, but for practical work, it is important to organize oneself well. Yes, we could start with the 30 datasets in clics3, and tick off, what they have.

**Comment by SimonGreenhill** [comment]
Yes -- I appreciate @xrotwang's arguments about not maintaining a catalogue, but I think for getting us to 1.0, and making sure that all datasets we release then are as 'perfect' as they can be, it makes sense to track this. Especially since what we mean by a 'perfect' dataset keeps evolving

**Comment by LinguList** [comment]
Also, if one thinks practically, that we want to show a list for the first release: in this case, we'd already have it...

**Comment by xrotwang** [comment]
Ok, trying to make 1.0 as uniform as possible is important, I think. So yes, let's have a table in the wiki. But hopefully a very uniform 1.0 will be enough incentive for further to contributions to abide by the rules without much monitoring :)

**Comment by xrotwang** [comment]
So, should I seed a markdown table with what we get from Zenodo right now?

**Comment by SimonGreenhill** [comment]
ja, bitte!

**Comment by xrotwang** [comment]
https://github.com/lexibank/lexibank/wiki

A lot of unreleased datasets are missing from this list, of course.

**Comment by LinguList** [comment]
I just modified this, by putting some people's names in brackets, suggesting that we change the patron, and also putting my names in those projects, where I have been working so much recently, that it is more logical if I take responsibility (practically speaking). E.g. Solomon, Tryon, etc., is best patroned by @SimonGreenhill, etc. So I put the current patron in brackets and encourage you to modify this by putting your name then first in the contributors, or assigning the role "patron" to yourself?

I also removed Mei-Shin from the patron position, as this is too much responsibility for a doctoral student: The patrons need to react and modify in times of releases, and this is also a bit difficult.

There are still a couple of things that should be done. But I suggest, everybody of our core team just re-evaluates the datasets they are responsible for and checks them thoroughly. I already assigned to issues there.

**Comment by chrzyki** [comment]
Happy to patron more datasets. I've been working in a couple of them for a bit but I'm not sure which ones I could take. Happy about suggestions/assignments.

**Comment by LinguList** [comment]
Thanks, @chrzyki, for me, it is important to answer for all CALC datasets, so either me or Tiago will take them. But datasets beyond this are very welcome to be taken. You can have a look at the people I put in brackets in our list.

**Comment by chrzyki** [comment]
Hiya @SimonGreenhill, looks like the table broke with your revision:

![table](https://user-images.githubusercontent.com/4689035/61932213-0fabba80-af83-11e9-9bbb-843d69bfa64f.png)

Could you revert this? Should I do this?

**Comment by LinguList** [comment]
@chrzyki, just thought: the Uralex is something you could patron. And there are hopefully incoming lists of African languages in Reflex. Plus a lot of smaller things, like the Semitic cognates, etc., which are not here yet, but in the catagory "data people agreed us to help with". We should in any case expand the table, also with these new datasets (see e.g. [liusinitic](https://github.com/lexibank/liusinitic) which I did yesterday, but do not plan to publish just as is, as I typed off the data myself).

**Comment by chrzyki** [comment]
Uralex sounds good, wanted to put that forward as well. Also happy to take the 'incoming' datasets you mentioned. Also:

- halenepal
- NorthEuralex
- wold
- ids
- diacl

**Comment by LinguList** [comment]
Yes, all fine, I'd say, except: NorthEuralex was heavily modified due to the orthography profiles by @tresoldi, who may want to keep maintaining this (or start), and I'd take care of halenepal, as it is just the ST languages, which we'll handle also as part of calc.

**Comment by chrzyki** [comment]
Sounds good! I'll also have another look once the table is in better shape again.

**Comment by LinguList** [comment]
for me, itworked nicely, the table.

**Comment by chrzyki** [comment]
But everything is shifted? IDs don't match Names etc. See my screenshot above.

**Comment by LinguList** [comment]
Ah, @chrzyki, in fact, three datasets for published papers by Thiago Chacon, chaconbaniwa, chaconarawakan, and chaconcolumbian were done by me to help Thiago Chacon to publish the code, which he had not done with the paper by then. They are quite straightforward, and the conceptlists could be added to concepticon. If you take the role for those, you could also add the concept lists. This would in fact be nice.

**Comment by LinguList** [comment]
> But everything is shifted? IDs don't match Names etc. See my screenshot above.
Ah, now I see...

**Comment by SimonGreenhill** [comment]
oops, sorry, yes pls fix

**Comment by chrzyki** [comment]
Will take care of it, please don't edit. :)

**Comment by chrzyki** [comment]
Should be fixed, please check ...

**Comment by chrzyki** [comment]
Oki, I've updated a couple of entries. Happy to take care of the Chacon list and their respective concept lists!

**Comment by LinguList** [comment]
I was just thinking: if this is also for practical reasons, to have some document to check against, we could as well use a google sheets table, right? Once data are released, etc., this is another matter, as already discussed, but for practical purposes, it would just be useful to exchange primary information here: size of dataset, who's the patron, status (version), etc. @schweikhard started a sheet that we used to trace which datasets are morpheme-segmented, but we could use that as a general sheet to check also where we haven't yet a version, etc.?

**Comment by SimonGreenhill** [comment]
Thanks Christoph -- sorry for the hassle!

**Comment by LinguList** [comment]
Issue's getting too long, but we should have this figured out now: patrons are responsible for that, and should make sure their data is in this state. If a dataset has no concepticon, this is also retrievable. It is more a problem of patrons' responsibility. By iterating over datasets and systematically checking, what's lacking, this can be easily identified. Hnadling it on the code-basis would be too much. If each of us has 10-20 datasets to patronize, we should be able to handle this, at least for the time being.
