### ISSUE TITLE
Update to HTTPS links

### ISSUE THREAD

**Issue by chrzyki** [lexibank/pylexibank#109]
We still have a lot of HTTP links in this repository, e.g. https://github.com/lexibank/pylexibank/blob/master/src/pylexibank/cldf-metadata.json. This leads to HTTP links in, e.g., all the metadata files. See for example:

https://github.com/lexibank/suntb/blob/master/cldf/cldf-metadata.json

Not urgent, but nice to have in the future.

**Comment by xrotwang** [comment]
I don't think I'd want to change the ontology URLs. Maybe we could do this with CLDF 1.1. From my point of view, these URLs are identifiers, so any processing software doing strict string equality check on them is doing the right thing. Or in other words, processing software should be required to only compare host and path of URLs in the ontology.
