### ISSUE TITLE
Include Latitude,Longitude by default

### ISSUE THREAD

**Issue by LinguList** [lexibank/pylexibank#111]
I ran into problems when trying to find the actual location via glottolog, as we have some datasets in which the glottocodes are wrong, or pointing to a top-level-family now. It would be good to check if we can find a geo-location. I started adding the geolocations for dialects to the SEA datasets, as we have good knowledge where they are from the sources, but it would be good to have some formal check.

**Comment by SimonGreenhill** [comment]
Given that Latitude and Longitude are default fields we should get them from glottolog and use them, unless they're overridden by the dataset.

**Comment by xrotwang** [comment]
How would a formal check look like? Datasets do not have to put Glottolog's numbers into `cldf/languages.csv` - although I'd interpret empty coordinates in a dataset as "we are fine with whatever Glottolog thinks is appropriate". Can we close this?

**Comment by LinguList** [comment]
I made a check for my subsets, and the idea was:

1. check if coordinates are there
2. if not, try to retrieve them from glottolog (as they are often needed in cldf)
3. if the glottolog is not valid or glottolog does not deliver coordinates, ignore it, and leave them empty

This can always be done in normal datasets, but I thought it would be helpful to retrieve them coordinates once from glottolog, as they are listed as default in the languages.csv file, and it would be one of the major advantages of linking to glottolog.

**Comment by SimonGreenhill** [comment]
Yes, i just hate having all empty default columns. I like Mattis’ solution above. This would mean that its really clear if there are no locations (case 3) and the dataset providers are probably in a good place to add these (amd hence into glottolog).
