### ISSUE TITLE
Enhance the templates for new lexibank datasets

### ISSUE THREAD

**Issue by LinguList** [lexibank/pylexibank#112]
After quick discussion, we thought that it would be useful to enhance the templates for new lexibank datasets:

* add the clean_form but uncomment it
* add the custom langauge class, the custom concept class, with import statement, but leave them uncommented

There are probably more things, but they seem to be crucial for avoiding the problems we have now, that people code differently, because they do not think of what is already done.

**Comment by xrotwang** [comment]
So, the basic idea is to show all the bits that can / should be overwritten in the template dataset? We can do that. But the template is surely not the best place to document best practices.

**Comment by LinguList** [comment]
I think, with the new architecture, that requires one to be explicit about add_froms_from_values, etc., we already will circumvent problems. 

What we probably also will need is would be some more code-review, as these errors all passed (also many unnecessary imports, as I just saw, when adjusting to v2), without being noticed. So I think: 

* our lexibank core team should be all basically on the same page with respect to code
* it would not hurt to uncomment the split_values form in a new template, because I look it up everytime anyway, so why not expose it, and uncomment it (specifically since the methods bounce values back and force)

The templates I think about are like the onces in the sphinx conf.py, where you see all things going on, but ignore most of them to stick to defaults.

**Comment by xrotwang** [comment]
@LinguList  happy enough now to close the issue? If not, assign to milestone 2.1.
