### ISSUE TITLE
Bug in `dataset.Dataset.split_forms`

### ISSUE THREAD

**Issue by LinguList** [lexibank/pylexibank#122]
See [here](https://github.com/lexibank/abvd/issues/3).

**Comment by SimonGreenhill** [comment]
Just encountered this in `birchallchapacuran` too. @xrotwang -- any idea about the best way to fix this?

**Comment by xrotwang** [comment]
@SimonGreenhill Does @LinguList 's suggestion here https://github.com/lexibank/abvd/issues/3#issuecomment-538724836 fix your problem as well?

**Comment by Bibiko** [comment]
I added in class Dataset:

    # TODO quick fix to avoid https://github.com/lexibank/pylexibank/issues/122
    def split_forms(self, item, value):
        return filter(None, [self.clean_form(item, form)
                    for form in split_text_with_context(value, separators='/,;')])

**Comment by SimonGreenhill** [comment]
No doesn't solve it..?

**Comment by LinguList** [comment]
Same error message?

**Comment by SimonGreenhill** [comment]
yes, same error, and yes, I think we need tobe more explicit here.

**Comment by LinguList** [comment]
I'll try and have a look tomorrow. Having an error is good, in any case, as this would have passed before, and `?` as a form is also not nice for clics and all other apps that could make use of the data.

So I'll look at birchall first, as this is smaller, and easier to debug, I hope....

**Comment by LinguList** [comment]
This means, abvd is another piece of cake, will have a look now.

**Comment by LinguList** [comment]
I found the problem, will make a PR to bugfix this soon.
