### ISSUE TITLE
Add pylexibank version and git repos commit into CLDF metadata

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#123]
It would be helpful to include the pylexibank version and git commit ID into the cldf-metadata as we do for concepticon-data and glottolog:

```json
  "notes": [
        {
            "dc:title": "environment",
            "properties": {
                "glottolog_version": "v4.0",
                "concepticon_version": "v2.1.0-47-g4730b7c"
            }
        }
    ],
```

Oh -- and CLTS too.

**Comment by SimonGreenhill** [comment]
Now gives:
```json
             "properties": {
                 "glottolog_version": "v4.0",
                 "concepticon_version": "v2.1.0-5-g49dc47d",
                 "pylexibank_version": "1.1.2.dev0",
                 "repository_version": "f5fa733"
             }
```

**Comment by xrotwang** [comment]
I'm thinking about this again. For the catalogs, like Glottolog and Concepticon, I have a solution using `gitpython`. For the python packages, otoh, I'd now tend to simply run something like
```bash
pip freeze > cldf/requirements.txt
```
writing  `requirements.txt` to the `cldf` directory. We could link to this file from within the CLDF metadata, with something like
```python
"prov:wasGeneratedBy": [
    "python": "3.5.2",
    "python-packages": "requirements.txt"
]
```

**Comment by xrotwang** [comment]
@SimonGreenhill @chrzyki @tresoldi @LinguList 
So here's my proposal:
```python
    "prov:wasDerivedFrom": [
        {
            "rdf:type": "prov:Entity",
            "dc:title": "Glottolog",
            "rdf:about": "https://github.com/glottolog/glottolog",
            "dc:created": "v4.0-51-gd1fd2f4"
        }
    ],
    "prov:wasGeneratedBy": [
        {
            "dc:title": "python",
            "dc:description": "3.5.2 (default, Nov 23 2017, 16:37:01) "
        },
        {
            "dc:title": "python-packages",
            "dc:relation": "requirements.txt"
        }
    ],
```

**Comment by tresoldi** [comment]
Maybe besides the `dc:description` we should have a `dc:version` for Python? (here, 3.5.2) The information on when Python was compiled can pinpoint to (extremely unlikely) problems triggering some implementation bug, but for assessing reproducibility we need only the version.

**Comment by xrotwang** [comment]
Note that there is no `dc:version` property in [DCMI Metadata terms](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/). I've changed the code to now only include the version, which - as you say - is really what we want.
