### ISSUE TITLE
Workflow suggestions for creation of forms and segments in pylexibank 2.0

### ISSUE THREAD

**Issue by LinguList** [lexibank/pylexibank#127]
Here's how the workflow should run, for pylexibank 2.0, as I think now:

1. a Dataset has three default attributes, (1) a list of brackets, as defined in `clldutils.text.split_text_with_context`, and (2) a list of separators, as passed to `pylexibank.dataset.split_forms`, where it should be defined (not the case yet), and (3) a list of forms that need to be treated as meaning "missing entry", as defined implicitly now in `pylexibank.dataset.clean_form`
2. we have three ways to add lexemes: (1) add_forms_from_value means to rely on pylexibank's splitting functionality and to further segmentize the data if a profile is provided, (2) add_form means to split the forms independently, and segments them if a profile is provided, (3) add_segments adds all datapoints independently

This results in the following re-organization (with new function calls), first for **individual datasets** (here **overriding defaults**):

```python
from clldutils.text import BRACKETS

class Dataset(BaseDataset):
    separators = "/,;"
    brackets = BRACKETS
    missing_data = ["-", "---", "*", "?"]
```

To guarantee that this works, the function calls need to be updated, first `pylexibank.dataset.split_forms`:

```python
def split_forms(self, item, value, separators=None, brackets=None):
    brackets = brackets or self.brackets
    separators = separators or self.separators
```

Then, `pylexibank.dataset.clean_form`:

```python
def clean_form(self, item, value, missing_data=None):
    missing_data = missing_data or self.missing_data
```

**Comment by LinguList** [comment]
The benefits are that we can then add the statements on our major operations, namely brackets, separators, missing data, to each dataset, which helps debugging and also increases awareness of our typical workflows.

**Comment by LinguList** [comment]
@xrotwang, @SimonGreenhill, I hope this is clear enough?

**Comment by SimonGreenhill** [comment]
Hi Mattis, this looks good. One thing though is that I'd rather be less explicit with brackets and get them to raise errors, so a default like this might be better:

```python
BRACKETS = { "(": ")", }
```

**Comment by LinguList** [comment]
see #128 
and [naganorgyalrongic](https://github.com/lexibank/naganorgyalrongic) for an example on the usage of brackets, separators and missing_data

**Comment by LinguList** [comment]
From my side, this also seems to be about it: we may do a bit more later, but we have now all major components in place, and in a way that one can add the relevant attributes to the Dataset class, as I think will be more explicit, and could also be written to the markdown later. I started tagging issues with milestone, so we should also have a look at them and decide if its feasible to do that for 2.0 or later.
