### ISSUE TITLE
add_concepts() & add_languages() returns

### ISSUE THREAD

**Issue by chrzyki** [lexibank/pylexibank#130]
Calling `add_concepts()` (or `add_languages()`) to populate the respective dataset information and then building a concept or language mapping for lookup operations during `add_form()` (or similar) feels not very elegant (or am I missing a better way of doing this?).

It would be neat if the return of the respective method (`add_concepts()`, `add_languages()`) already could serve as a lookup table, particularly in conjunction with `id_factory=`.

**Comment by xrotwang** [comment]
So you suggest we return a `dict` mapping - what exactly? - to the result of `id_factory`, right? But how would we specify the keys?

**Comment by LinguList** [comment]
It's a bit different, I think. What we usually have is:

1. wordlist with concept glosses
2. `etc/concepts.tsv` linking concept glosses in wordlist to an ID

So when converting to cldf, we need to usually store the ID for each concept gloss, in both ways: if I iterate over the wordlist, I need to get the `Parameter_ID`. To do that, we usually now have almost always a statement like the following in the code (me using dict-comprehensions now to have less lines):

```python
gloss2concept_id = {concept.english: concept.id for concept in self.conceptlist.values()}
```

or
```python
gloss2concept_id = {concept['ENGLISH']: concept['ID'] for concept in self.concepts}
```

To avoid these statements, one could have the `add_concepts` function (and `add_languages` as well) return the dictionary right away. All one would need is:

1. specify in the function which column should be the ID, assuming that we have to work on CONSITENT IDS in `etc/languages.tsv` and `etc/concepts.tsv` and not leave that to the code (so no more slugging, better: slug in `etc/*`).
2. specify which colum we expect in the original data. 

So a possible call signature would be:

```python
cmap = app.writer.add_concepts(ID='ID', SOURCE="ENGLISH")
```

```python
lmap = app.writer.add_languages(ID="ID", SOURCE="Name")
```

I am not sure if "source" and "id" are the best terms here, but the principle is: one is the id we give, one is what we still need to convert the original form into the ID.

**Comment by xrotwang** [comment]
see #133
