### ISSUE TITLE
Auxiliary scripts for debugging/developing

### ISSUE THREAD

**Issue by tresoldi** [lexibank/pylexibank#132]
I was preparing a PR for a unique slugger, as discussed this morning. The code and and example with the Allen-2007-500 conceptlist using both English and Chinese can be found in this [gist](https://gist.github.com/tresoldi/f2de437a81a0e934300bceb6437a3a2a).

We could have more auxiliary scripts, for example one I use for ordering orthographic profiles (the NULLs at the top, then sorted by length and alphabetically, so that diffs are easier). As such, what should be the entry points for these scripts? Should they even be part of `pylexibank`, or we should have them in `cldfbench`?

**Comment by xrotwang** [comment]
I'd say this is rather a candidate for inclusion into `pylexibank.util` than a separate cli script, because It looks as if this functionality would always be called by code. If we include it, it should be possible to use this together with the `id_factory` argument to `add_languages` et al.

**Comment by xrotwang** [comment]
I don't know exactly how to do this, though, since it requires a second pass through the data.

**Comment by xrotwang** [comment]
Hm, I guess that would become black magic pretty quickly. So maybe we just have a recipe somewhere along the lines of:
```python
lmap, labels = [], []
for i, lang in enumerate(self.languages):
    labels.append(lang['Name'])
    lmap.append(lang)
lmap = collections.OrderedDict(zip(slugids(labels), lmap))
```
The next question is, how would code further down the line, e.g. when adding lexemes, figure out the language ID? Presumably via some unique property of language that hasn't been used to build the slug. So this would require another lookup:
```python
lookup = {v['unique_prop']: k for k, v in lmap.items()}
```
Or am I misunderstanding something?

**Comment by LinguList** [comment]
I think we don't need to check for uniqueness when creating "speaking" language ids from a concepticon conceptlist, as one could just follow the following id_factory argument:

```python
id_factor = lambda x: x['ID'].split('-')[-1]+'-'+slug(x['English'])
```
Since our concepticon IDs (if we talk about concept lists) are always unique, this will guarantee uniqueness in any case, as I mentioned in the kitchensemitic discussion, so instead of the long statement, we'd just have `1-hand`, `2-foot`. So we gain readability when checking cldf and also keep unique ids here. 

Along with the suggestion to return the lookup in the `writer.add_concepts` function (and `add_languages` as well), this could be made the default, and it would ALSO work for a custom list in `etc/concepts.csv`, since the `x.split('-')[-1]` will return the full ID if it does not contain a dash, and the normal case is that the ID is numeric, if one makes a new concept list.

**Comment by tresoldi** [comment]
Two things:

- If we add some kind of enumeration to all labels, the complex logic with an iterator and lazy evaluation is not needed, totally agreed -- we can try to elaborate complex scenarios where this would not be feasible or desirable, but in those cases we would manually fix ids anyway.

- I had understood that the idea was to have an independent tool that would help writing the languages/parameters files, kind of a linter, with the dataset code reading the pre-computed IDs from `etc/`. That is why the script is reading raw tabular data and writing to stdout. Did I misunderstand it and you are thinking of having something similar as part of the CLDF creation, as some factory?

**Comment by xrotwang** [comment]
@LinguList What would the lookup to return be? You'd have to somehow derive the relevant input to `id_factory`, right? Or would you return just `zip(self.languages, [list-of-ids])`?

**Comment by xrotwang** [comment]
@tresoldi I see, so this would be a tool to prepare stuff that might go into `etc/`. In that case, yes it should be separate. Maybe it could even live in a gist, or cookbook entry?

**Comment by tresoldi** [comment]
@xrotwang Yes, I suppose it could very well live in a cookbook, or perhaps in a repository of its own, along with any other tool we might come up with. Really useful things, if any, could migrate to pylexibank in the future.

If that is the case, feel free to close the issue and having me hosting them in some `tresoldi/lexibank_stuff` repo for the time being. :wink:

**Comment by LinguList** [comment]
@xrotwang: the most common case, as outlined in #130, is the inverse dictionary, so the function would have the following signature:

```python
def add_concepts(id_column="ID", reverse_id="ENGLISH", id_factory=None):
    id_factory = id_factory or lambda x: x["ID"].split('-')[-1]+'_'+slug(x["ENGLISH"])
    ...
    return {dictionary with reverse_id as key and ID as value}
```

And for languages, it would be probably simpler as we do not have the rigorous concepticon IDs:

```python 
def add_languages(id_column="ID", reverse_ID="Name", id_factory=None):
    id_factory = id_factory or lambda x: x
    ...
    return reverse_ID_lookup
```

While some datasets need to further tweak these parts, the majority of datasets could be addressed with this modification.

**Comment by LinguList** [comment]
An alternative would be a function `get_id_by_value` that looks up the cldf-dataset, searches for a value, and then returns the ID. This could be used in:

```python
writer.add_form(
    Form=Form,
    Parameter_ID=writer.get_id_by_value("concept", "hand", "Name",
    Language_ID=writer.get_id_by_value("language", "German", "Name")
)
```

**Comment by xrotwang** [comment]
@LinguList ah, ok, an explicit `lookup_factory` argument would do. We can inspect what's passed in, and if it's a `str` and not a callable just use it as `dict` key. If a `lookup_factory` is passed, we return a `dict`.

**Comment by LinguList** [comment]
Yes, excellent, that would do the trick! And it is also non-intrusive, so it won't break the code of existing datasets.

**Comment by SimonGreenhill** [comment]
done, right?
