### ISSUE TITLE
Unnecessary output by add_concepts?

### ISSUE THREAD

**Issue by tresoldi** [lexibank/pylexibank#135]
Add concepts is currently printing the attributes of each element: https://github.com/lexibank/pylexibank/blob/b2b24aafcbe618f08ef994d8e0ce2d29f601bff1/src/pylexibank/cldf.py#L307

Is this intended? Should we maybe have it with a `debug` flag?

**Comment by LinguList** [comment]
Yes, see specifically #136.

**Comment by xrotwang** [comment]
Ah, no. That's a leftover from debugging.

Johann-Mattis List <notifications@github.com> schrieb am Fr., 25. Okt.
2019, 13:45:
