### ISSUE TITLE
concepts in `parameters.csv` cannot be flexibly expanded when using `args.writer.add_concepts`

### ISSUE THREAD

**Issue by LinguList** [lexibank/pylexibank#136]
The problem is, that our lookup only functions now for restricted parameters and languages, as it asssumes a global namespace of some 4/5 attributes, like Name, Concepticon_ID, and Concepticon_Gloss. 

So if I have a custom concept class, with, say, one additional argument, the only way to pass this through for now is to add the additional arguments manually, since I change name spaces (from conceptlist in concepticon to cldf).

So I have:

```python
@attr.s
class CustomConcept(Concept):
    Chinese_Gloss = attr.ib(default=None)
```

But the Chinese_Gloss is called "CHINESE" in `Beida-Sinitic`, so the mapping from CHINESE to Chinese_Gloss cannot be guessed, of course, by the `add_concepts` method. 

I wonder what to do:

1. I could stick to the `add_concept`, where I have full control, or if we could
2. add some `**namespace` attribute to the `add_concepts` call that would collect all key-value-pairs here, and add them via `add_concepts` in the function (cldf.py line 300):

```python
            attrs = dict(
                ID=id_,
                Name=c.label,
                Concepticon_ID=c.concepticon_id,
                Concepticon_Gloss=c.concepticon_gloss)
            for name, space in namespace.items():
                attrs[space] = c.attributes[name]
```

Even better would be if we could handle this on the level of the concept class, but I don't really know how. E.g.:

```
class NewConcept(Concept):
    Chinese_Gloss = attr.ib(default=None, metadata={"name_in_source": "chinese"})
```

**Comment by LinguList** [comment]
An obvious workaround is to just avoid using `add_concepts` for the time being, and using explicit `add_concept`

**Comment by xrotwang** [comment]
Will look into this later today.

Johann-Mattis List <notifications@github.com> schrieb am Fr., 25. Okt.
2019, 13:41:

**Comment by LinguList** [comment]
Okay, for the time, I'll make explicit `add_concepts`, where needed, as this is anyway a wrapper around it.

**Comment by LinguList** [comment]
Okay, but how do I work now, if my concepts are in concepticon, and they are all uppercase there, but rendered lowercase, but my attribute class wants to rename, what we name "chinese" in the concepticon-conceptlist to "Chinese_Gloss" in `parameters.csv`, as this is the name in my `CustomConcept`? I do not see how I should solve this here. Or what should I write in the lookup?

How can I do what I do below with `add_concepts`?

https://github.com/lexibank/beidasinitic/blob/c2078953d0a94c2e9732e128e15d1ccaf09ef1f6/lexibank_beidasinitic.py#L57-L67

**Comment by xrotwang** [comment]
Complete renaming isn't possible, but looking up custom columns in `Concept.attributes` uses lowercase keys, and inserting the values into the `dict` which is fed to `lookup_factory` uses the attribute names of the `concept_class`. So using `Chinese` as attribute name for the custom concept class and consequently as `lookup_factory='Chinese'` should work.

**Comment by LinguList** [comment]
Yes, exactly, so from that end, it means I have to add the concepts one by one then, unless we add a consistent re-writing routine of the name spaces. We do this by now for the four major parts of concepticon, but not for more potential attributes. And since the namespace in concepticon is by now quite different from CLDF, I think it is better to work on good consistent names here (like `Chinese_Gloss`, which is my term for a Chinese translation by now), and add them concepts one by one, than to inherit naming conventions from concepticon. 

Well, I guess I have to think about it. Maybe following concepticon is also fine. But I'll leave it explicit for now.

**Comment by xrotwang** [comment]
Yes, it's a bit confusing. But I think there are just two options:
- rewrite explicitly, because the new names are "better",
- leave as in concepticon - **including** the casing.

Taking over the concepticon conceptlist columns with different casing is the worst option, I think.

**Comment by LinguList** [comment]
Yes, I agree.
