### ISSUE TITLE
coordinates are written as default in cldf, but they are not a default in our language class

### ISSUE THREAD

**Issue by LinguList** [lexibank/pylexibank#138]
So one needs a custom-language-class to include coordinates, and cannot add coordinates if one has the normal class.

**Comment by LinguList** [comment]
I learned about this when preparing [lexibank/joophonosemantic](https://github.com/lexibank/joophonosemantic).

**Comment by xrotwang** [comment]
fixed in https://github.com/lexibank/pylexibank/commit/3b33797c42f38535c224c798da8e860f468f9e7d
