### ISSUE TITLE
concepticon concepts take precedence over ./etc/concepts.tsv

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#139]
If a dataset has a concept list in concepticon, this is given precedence over ./etc/concepts.tsv. While ./etc/concepts.tsv is loaded into `Dataset.concepts` the concepticon list is loaded if `.add_concepts()` is used:

https://github.com/lexibank/pylexibank/blob/71f6135b0373add6e9e920e8f3aac0a40b9b9b41/src/pylexibank/cldf.py#L265-L268

So, this means we can't override the concept list using ./etc/concepts.tsv.  While defaulting to the concepticon version is useful for keeping the lexibank dataset in sync with concepticon, it might be an issue in some cases. 

For example, the zgraggenmadang dataset has the raw data taken from transnewguinea.org and stored in ./raw/madang.csv. The concepts in ./raw/madang.csv are named according to transnewguinea.org's slugs. The concept list in ./etc/concepts.tsv contains the correct slug -> zgraggen -> concepticon mapping. So generating the Parameter_IDs means using the slug in concepts.tsv to get the correct parameter ID. If I use `add_concepts` this loads the mapping from concepticon.

I'm not sure what the alternative is:
1. Should we try to merge concepticon and and concepts.tsv? this seems a recipe from problems. 
2. Should we allow concepts.tsv to override concepticon? this could be useful but it means we need to actively delete ./etc/concepts.tsv when we can.
3. Leave as-is and work around it by adding the concepts manually. But then changes to concepticon won't percolate through to this wordlist.

For zgraggenmadang, I'm currently debating whether to add the concepts manually, or changing the raw data (madang.csv) to match.

**Comment by LinguList** [comment]
I usually try to make local corrections, if needed, to a given concept list. So only the name is corrected, as you can see here:

https://github.com/lexibank/joophonosemantic/blob/f560e9cdffb77e5d87ad77d50030e56020aef06a/lexibank_joophonosemantic.py#L53-L54

The major idea is: if we change concepticon, this will still be persistent. 

We have, unfortunately, this problem in quite a few conceptlists. But there's no way around this: People often cite an official concept list in a text that we link to concepticon, but their excel spreadsheet contains other concepts. It is annoying but true. 

The re-mapping, albeit annoying, seems to be the best way to handle this.

**Comment by SimonGreenhill** [comment]
Yeah, I think this is the safest option. It's ugly, but I think it's better than having some magic override etc

**Comment by LinguList** [comment]
Generally, to increase awareness, any dataset on concepticon could also offer the actual names. In this way, it would again be easy to deal with this, as it would just be a column with an ID or a slugged thing that helps you to map the data.

**Comment by xrotwang** [comment]
I'm for leaving as is, following the principle of

> Simple things should be simple, complex things should be possible.

Here, the simplest - and in fact prefered/recommended - method to add concept info to a dataset is via a proper and complete Concepticon concept list. While this adds administrative overhead, it's still what we want to push.

**Comment by xrotwang** [comment]
@SimonGreenhill I think the "merging concept info" is the most complicated scenario - and I'd like to avoid it if possible. So rather than merging, I'd go for curating `etc/concepts.tsv` up to a point where it can be submitted as concept list to Concepticon - even if this supersedes an incomplete list which is already in Concepticon.

**Comment by tresoldi** [comment]
I am running into a similar problem with some datasets, such as `kraftchadic` and `tls` (concept reuse, etc.). Is it ok to carry a full `etc/concepts.csv` while we decide on that? One of the advantages is that we can precompute the IDs and store them in the concept file itself, with no need for id factories in code.

**Comment by SimonGreenhill** [comment]
Sounds good @xrotwang

**Comment by xrotwang** [comment]
@tresoldi I'd say yes. In the worst case this may result in an almost-duplicate list added to Concepticon - but this will mirror the way we gained knowledge.

**Comment by LinguList** [comment]
In many cases, though, it is just enough to add a dictionary that refines some concepts, as you will be able to see in many lists, like `bowernpny`, but also `joophon*`, where there were just two cases of inconsistencies. Here, one can resolve the problem silently, by adding a small dictionary to the code.

**Comment by xrotwang** [comment]
@LinguList but that's cases where the mapping from form to concept needs to be fixed, right? Not cases where the actual Concepticon data needs to be amended. These latter cases are the problematic ones, I think, and these should be avoided, because we don't want "inofficial but better" concept lists living in a datasets' `cldf/parameters.csv`.

**Comment by LinguList** [comment]
Yes, I completely agree. If one list is better, and one believes that, as we could directly confirm for Huber-1992-375 already, one needs to work on a better conceptlist in concepticon. And if differences turn up, as in some lists, where the publication has one version and the appendix another version, these should ideally both be documented in concepticon, by having an additional `English_in_Appendix` or similar, that could then be used when creating a lexibank dataset.
