### ISSUE TITLE
Segmentation should be the explicit responsibility of each dataset

### ISSUE THREAD

**Issue by xrotwang** [lexibank/pylexibank#14]
To make segmentation/tokenization more transparent, `pylexibank` shouldn't provide too much support, obscuring what's going on. I.e.
- no segmentation should be done by default
- no segmentation should be done across multiple dataset by shared code in a `pylexibank/provider` module.

Automatic segmentation when adding lexemes to the CLDF dataset can be triggered in two ways only:
- by providing an orthography profile or
- by providing a `Dataset.tokenizer` property, returning a suitable callable.

**Comment by xrotwang** [comment]
@SimonGreenhill @tresoldi @LinguList @chrzyki This is more a design spec than an issue or a question. Your agreement is assumed :)

**Comment by chrzyki** [comment]
Sounds very reasonable.

**Comment by tresoldi** [comment]
Agreed. And people can always look at already implemented datasets when in doubt.

**Comment by SimonGreenhill** [comment]
👍
