### ISSUE TITLE
"Linter" for orthographic profiles

### ISSUE THREAD

**Issue by tresoldi** [lexibank/pylexibank#141]
As previously discussed ([here](https://github.com/lingpy/reproducible-data-paper/issues/78), [here](https://github.com/lexibank/naganorgyalrongic/issues/4), and in person), I've been using something between a linter and a formatter for preparing the WOLD profiles.

The code is here, essentially the formatter: https://gist.github.com/tresoldi/023c1588f66b70907b269c4aa640faa3

I find it useful because it (1) puts the entries in an order that I find intuitive and is fixed (and can be easily adjusted), (2) makes some corrections by itself (such as always outputting the normalized BIPA, solving problems like my apostrophes in `naganorgyalrongic`), and (3) makes diffing more sensible (not only "historically", as in git, but for actual comparison between different profiles, such as for related doculects/languages -- think about comparing the American and British transcriptions for the same English wordlist).

An example of the results is the correct orthography profile for the same dataset: https://github.com/lexibank/naganorgyalrongic/commit/950b5e616b096445fea545a7106627a81c0ce666#diff-a432be3c4d87235f644b26e39ef696f4 (sorry, can't find a way to link to a single-file diff)

Should we add something similar to our toolbelt?

**Comment by SimonGreenhill** [comment]
Cool!

**Comment by tresoldi** [comment]
Great that you like it! I can incorporate back some of the checks I have -- most are for stupid things I keep doing, should be a good starting point as any.

I'll keep it as an independent script for the time being, we can merge it later.

**Comment by SimonGreenhill** [comment]
Where are we on this?

**Comment by tresoldi** [comment]
I've been slowly working towards it, it is the code at https://github.com/tresoldi/lexibanktools/

While it is still somewhat held with duct tape, I already used it for some datasets (wold, utoaztecan, some by MeiShin). It should be integrated to lexibank as a "normal" command, I was waiting for decisions in terms of how much should other libraries, such as `segments`, should be changed (e.g., I am applying the profiles manually, as with segments I cannot count how many times each rule is triggered, an information which is needed for both updating the frequency column and removing unused rules)

**Comment by LinguList** [comment]
@tresoldi, I think the best is to come up with a concrete PR, instead of waiting on decisions from our side here. For me, maybe only for me, but I expect for at least some of the others as well, it is easier to see a piece of code and comment on it, instead of discussing about what needs to be changed in the implementation in the abstract. And it is specifically important to see how this integrates in lexibank as a simple command, with some usage examples.

**Comment by SimonGreenhill** [comment]
This looks like great progress @tresoldi, thanks! I'm keen to get this into the core lexibank library. It should be a relatively easy thing to drop in as a command (with many subcommands). We already have [check_profile](https://github.com/lexibank/pylexibank/blob/master/src/pylexibank/commands/check_profile.py) and [init_profile](https://github.com/lexibank/pylexibank/blob/master/src/pylexibank/commands/init_profile.py), so perhaps this can replace them with a single 'profile' command which has sub commands? (thoughts @xrotwang?)

**Comment by xrotwang** [comment]
@SimonGreenhill I'm not particularly keen on sub-sub-commands. Will check out @tresoldi 's code and see how it could be folded in.

**Comment by xrotwang** [comment]
@tresoldi how about we include your whole script as `lint_profile` command, which will do both, "format" and "trim" in your code?

**Comment by xrotwang** [comment]
closed in favour of #169
