### ISSUE TITLE
formspec normalise unicode

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#143]
Should formspec normalise combining diacritics?

**Comment by tresoldi** [comment]
+1 , but we need to make sure this does not interfere with existing orthographic profiles.

**Comment by LinguList** [comment]
Only, if you need it, as the orthoprofiles normalize already, so if it is needed for desegmentation, yes, but I think these are things that would become only relevant upon segmentation, right? So it's an orthoprofile problem.

**Comment by xrotwang** [comment]
See #148
