### ISSUE TITLE
add_from_cldf()

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#147]
We have some datasets already in CLDF, it would be useful to have a simple way of importing into lexibank format (adding lexibank's added value of segments etc etc). For example, [dravlex](https://github.com/lexibank/dravlex/blob/master/lexibank_dravlex.py) is pretty silly. It would be nice to be able to do something like:

```python
    def cmd_makecldf(self, arg):
        self.add_from_cldf(...)
        # added things...
```

**Comment by xrotwang** [comment]
[`pylexibank.providers.clld`](https://github.com/lexibank/pylexibank/blob/master/src/pylexibank/providers/clld.py) does something in this direction. It's not a lot of code, so I'm not sure whether generalising this would result in something useful - or equal amounts of configuration ...

**Comment by SimonGreenhill** [comment]
Yes, that looks promising, although the hardcoded clld.org url limits it (https://github.com/lexibank/pylexibank/blob/master/src/pylexibank/providers/clld.py#L14).  Perhaps we could make it a bit more general? I'll try and reimplement dravlex in it and see how I go.

**Comment by tresoldi** [comment]
It is also the case for `northeuralex` and `wold`.

**Comment by SimonGreenhill** [comment]
Closing this for now, as this wasn't too painful: https://github.com/lexibank/dravlex/blob/master/lexibank_dravlex.py
