### ISSUE TITLE
how to do a lexibank.download?

### ISSUE THREAD

**Issue by LinguList** [lexibank/pylexibank#149]
I just tried (did anybody else try it?) the `cldfbench lexibank.download DATASET`, but the command is not there, yet `cldfbench download DATASET` complains aboutt an invalid dataset spec. So how do I trigger the download command properly?

**Comment by chrzyki** [comment]
`cldfbench download lexibank_DATASETNAME.py` should work, i.e. run `download` directly against the Python file with the implementation of `cmd_download()`.

**Comment by xrotwang** [comment]
Also, `cldfbench download --entry-point lexibank.dataset DATASET` should work.

**Comment by SimonGreenhill** [comment]
Yes, I've been using @chrzyki's format.

**Comment by LinguList** [comment]
A, very good. I think it's important, that everybody who actually leaves the download statement in their data, will test, if it works. Otherwise, leaving raw data there, and just deleting the download command is also fine with me. E.g., if I crawl data from a website, it is often possible that the website will change structure, so the download command is not stable anyway, so explicitly saying: here's that data from that website that I downloaded there on X.Y.Z, is in my opinion also fine enough...

**Comment by xrotwang** [comment]
A successful run of `cldfbench download` will put a `README.md` with a timestamp into `raw/`.
