### ISSUE TITLE
Revise the slugging that happens on cognate

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#15]
I’m working on polishing the birchallchapacuran dataset, and making the cognate labels with

	cogid = '%s-%s' % (slug(r['Meaning']), r['Set'])

…which gives “old-A”, “old-B”, “old-C”. But this gets CLDF’d to chapacuran-olda. Is there anyway to keep that dash between “old" and the cognate set ID? In general I’d prefer to keep the ID as “old-B” as that matches the paper.

**Comment by xrotwang** [comment]
must be with outdated pylexibank. Are you on 0.3.0?

**Comment by xrotwang** [comment]
ah, ok. It's the lowercasing and dash. The `chapacuran` is no longer prepended.

**Comment by xrotwang** [comment]
I think keeping the case would be simple. But I wouldn't want to allow **all** punctuation. What about allowing `_` - underscore - as separator and converting `-` to it?

**Comment by xrotwang** [comment]
Ah, ok, `-` could be ok, too: http://cldf.clld.org/v1.0/terms.rdf#id

**Comment by xrotwang** [comment]
So we could sluggify conditionally: Whatever doesn't match the regex specified for CLDF IDs gets sluggified?

**Comment by SimonGreenhill** [comment]
I like the idea of minimal and conditional slugging -- especially for this column where automatic transforms run the risk of making nasty errors (e.g. if I had cognate set, I don't know, hand-s-1 and hands-1 then this could both end up as hands1).

Perhaps warnings could be generated when the regex fails to match?

**Comment by xrotwang** [comment]
Like so:
```
...
ValueError: invalid CLDF identifier LanguageTable-ID: Jar\xfa
lexibank-curator> 
```

**Comment by SimonGreenhill** [comment]
Agree -- most users aren't going to have to handle this, just those adding datasets. This is where we need to be strict.

**Comment by xrotwang** [comment]
ok. will implement and push 0.4.0 later today. You are only working in `lexibank_birchallchapacuran.py`, right?

**Comment by SimonGreenhill** [comment]
I'll push what I've got now.

**Comment by SimonGreenhill** [comment]
(and yes, only in lexibank_birchallchapacuran.py)
