### ISSUE TITLE
Support multiple profiles

### ISSUE THREAD

**Issue by tresoldi** [lexibank/pylexibank#151]
Do we have a standard way of supporting multiple orthographic profiles? Or should we try to always use a single file, even when the code and the profile become more complex?

My question concerns mostly WOLD, with 41 very different profiles (one per language). I couldn't find a non-hacky way (involving lambdas and the like) to tell pylexibank "use the language-id of each row as a tokenizer-id".

The `_tokenizer` in Dataset does accept a column name via `**kwargs` (https://github.com/lexibank/pylexibank/blob/021f37481d37b472715033033773543273ed301f/src/pylexibank/dataset.py#L152), but there are conflicts when a grapheme is missing from one or more profiles (e.g., in some language "ch" is just "c"+"h", and even redundantly listing all missing graphemes in all languages is not enough, as it can lead to inconsistencies, like consuming characters in the stream that are not supposed to be consumed).

Besides, it doesn't seem that LexibankWriter allows me to pass such information (cf. https://github.com/lexibank/pylexibank/blob/021f37481d37b472715033033773543273ed301f/src/pylexibank/cldf.py#L93), as it only takes `item` (the **kw passed to `add_form`) and `string` (the value to be segmented). 

Currently, while refining WOLD, I'm manually loading all profiles in a `tokenizer` dictionary, inside `cmd_makecldf()`, and calling it directly:

```python
for row in progressbar(lexemes_rows):
    args.writer.add_form_with_segments(
        Language_ID=row["Language_ID"],
        Parameter_ID=row["Parameter_ID"],
        Form=row["Form"],
        Value=row["Form"],
        Segments=tokenizer[row["Language_ID"]]({}, row["Form"]),
        (...)
```

Note that this is **not** urgent: CLICS3 won't depend on this (we don't need segmented data, and I'll get back to it after we resubmit).

**Comment by xrotwang** [comment]
A possibly less hacky way of doing this right now, would be overwriting `Dataset.tokenizer`. This could return a function that takes `item['Language_ID']` into acount when tokenizing (`item` is passed as first parameter to it after all).

But I'd propose a "full" solution right now (at least for the case of one profile per language id):
1. If `etc/orthography` is a directory, all `*.tsv` files are considered to be orthography profiles.
2. `Dataset.tokenizer` initialises a `dict` (mapping profile file stem to initialized `Tokenizer`).
3. The function returned by `Dataset.tokenizer` looks up a tokeinzer instance as follows:
   - If there is only one tokenizer, use it.
   - If there's a `dict` of tokenizers:
     - if a keyword `profile` is passed in the call, use its value as `dict` key,
     - otherwise use `item['Language_ID']` as `dict` key.

**Comment by tresoldi** [comment]
That would be great! Just for reference, the code was using is this: https://github.com/lexibank/wold/blob/profiles/lexibank_wold.py

And the profiles (still a bit behind my local changes) are these: https://github.com/lexibank/wold/tree/profiles/etc

**Comment by xrotwang** [comment]
@tresoldi have a look at #152. Moving your WOLD profiles into a directory `etc/orthography` and renaming to just `<Language_ID>.tsv` should make things work.

**Comment by tresoldi** [comment]
Thank you, @xrotwang ! I'll take a look after we merge WOLD, making sure it works, and get back to it once the CLICS submission is over.
