### ISSUE TITLE
Two more functionalities in FormSpec

### ISSUE THREAD

**Issue by tresoldi** [lexibank/pylexibank#155]
As I list at https://github.com/lexibank/tls/pull/9 and which were needed for `tls`:

- Allow to skip over entries if they match a given substring or set of substrings (or, even better, a regular expression)

- Allow regular expressions, perhaps forcing them to be in VERBOSE mode

**Comment by LinguList** [comment]
I am strictly against regular expressions, outlined in my [comment on tls](https://github.com/lexibank/tls/pull/9#issuecomment-549730714). I am also not sure if we need skipping, as we can easily pull out the entries of the data and place them explicitly into lexemes. We can, probably, discuss adding a SKIP entry into lexemes, to avoid that we have to redefine it in the `missing_data` of the form spec. So one could say that, e.g., NULL forces to ignore an entry, in all conditions, similar to orthography profiles. 

As I mentioned in the comment: the cross-reference entries are only about 30, and we are dealing with more than 100 000 words here. So it is an overkill to capture this case with a regular expression.

**Comment by xrotwang** [comment]
I tend to agree with @LinguList here. Regular expressions are Pandora's box here, I think. And I'm also concerned that with something like `excludes` we end up with too many ways to do similar things.
We already have
- `etc/lexemes.csv`,
- `missing_data`,
- `replacements`

**Comment by xrotwang** [comment]
Maybe we need to clarify some design goals? The way I see it, `FormSpec` is the place where you specify general assumptions about the lexical data in the dataset - basically your ideas about the conventions that have been used when the source data was assembled. It isn't meant to be the place to deal with exceptions to these rules, though. That's what `lexemes.csv` is for. If there are no discernible rules there are three options:
- lots of entries in `lexemes.csv`
- "garbage in, garbage out", i.e. just copy `Value` to (bad) `Form` (alhough you'd have to have very good reasons to do this, since it basically creates bad CLDF data - which goes against lexibank's core idea)
- the dataset is not amenable to "lifting" to CLDF

**Comment by LinguList** [comment]
Yes, this is important, @xrotwang. There is just one addon: if we cannot lift a value to a form, or if we have bad forms, this does not necessarily mean the data is full garbage, as there are cases where people deliberately code their data in this way, e.g., Chinese data in characters only. These data, however, may come with cognates, as `kitchensemitic`, so here, we have a clear-cut case of bad forms, but okayish data, as they supply cognate sets. So our conclusion with respect to cldf is: we would not honor those datasets and include them in CLICS (also for their small size in terms of concepts), and we would never segment them. If there's a dataset like, say, the Transeurasian collection of numbers in a word document, then, yes, any attempt to cldfify it would be futile...

**Comment by xrotwang** [comment]
One more note on the "garbage in, garbage out" option: I think lexibank does provide at least some assistance in recognizing such "bad" datasets: These datasets would presumably have
- a lot of errors flagged in the transcription report
- a very permissive `FormSpec` - i.e. no `separators`, etc.

**Comment by LinguList** [comment]
Yes, or they may never be lifted to transcriptions.

**Comment by SimonGreenhill** [comment]
Great, can someone summarise this into https://github.com/lexibank/lexibank/blob/master/CONTRIBUTING.md please?

**Comment by xrotwang** [comment]
@SimonGreenhill I'd say the design goal part belongs into https://github.com/lexibank/pylexibank/#the-cmd_makecldf-method while the part about the options when faced with "bad" data belong into CONTRIBUTING.md

**Comment by xrotwang** [comment]
voila: https://github.com/lexibank/lexibank/blob/master/CONTRIBUTING.md#formspec-should-capture-the-rules-used-to-compile-the-source-data

**Comment by tresoldi** [comment]
That is useful, thanks @xrotwang

**Comment by SimonGreenhill** [comment]
Awesome, thanks @xrotwang  -- I just want to get all these 'policy' type of decisions documented so we can all be consistent. Lexibank's advantage is consistency, so I want to maximise that!
