### ISSUE TITLE
dc:created property and differences 

### ISSUE THREAD

**Issue by chrzyki** [lexibank/pylexibank#156]
There is a difference on how the `dc:created` property is populated. I do, e.g.:

```bash
cldfbench lexibank.makecldf lexibank_halenepal.py --glottolog ~/Repositories/glottolog/glottolog --glottolog-version v4.0 --concepticon ~/Repositories/concepticon/concepticon-data/ --concepticon-version v2.2.0 --clts ~/Repositories/cldf-clts/clts/
```

With the respective catalogues simply at `master`. This results in: https://github.com/lexibank/diacl/blob/20838fdb670e1d8f4598e9cbaa50793d9a73e328/cldf/cldf-metadata.json#L33-L42

@tresoldi uses the other approach with `config.ini` and catalogues checked out at version tags (please correct me if I'm wrong). This results in: https://github.com/lexibank/wold/blob/de77283eb770f3cc44dbd28f3b66c7c02b41d099/cldf/cldf-metadata.json#L29-L39

Does this make any difference to us? Are either fine?

**Comment by tresoldi** [comment]
As @chrzyki pointed, I ran `makecldf` yesterday on a fresh environment (new virtual environment, deleting `~/.config/cldf`). After installing `pylexibank`, I setup the catalogs with `cldfbench catconfig`, and confirmed everything was running with `catinfo`. The hash shows up in the metadata as he linked:

```json
        {
            "rdf:type": "prov:Entity",
            "dc:title": "Glottolog",
            "rdf:about": "https://github.com/glottolog/glottolog",
            "dc:created": "v4.0-62-g552aa7f"
        },
```

**Comment by xrotwang** [comment]
@tresoldi `catconfig` only clones the repos, so will result in a repos with checked out `master` branch at `HEAD` revision. Note that [`552aa7f`](https://github.com/glottolog/glottolog/commit/552aa7f4e5bc3b841a4af32e34d44956ec32a269) is **not** tag `v4.0`. So to use the catalog at `v4.0`, you **must** use the `--glottolog-version v4.0` option to `cldfbench lexibank.makecldf`.

**Comment by tresoldi** [comment]
@xrotwang ok, no problem, I'll rebuild them now. But shouldn't we consider inverting the logic? If no commit/tag is provided, default to latest tag?

**Comment by xrotwang** [comment]
No. We want released versions to be used only. `552aa7f` is a commit hash (not a tag) of something that isn't on Zenodo.

**Comment by tresoldi** [comment]
Sorry, that is what I mean: if in a fresh environment I pip install `pylexibank` and run `cldfbench catconfig` (letting it populate `~/.config/cldf`), a call to `cldfbench lexibank.makecldf DATASET`, with no extra parameters, should default to the latest tag, and not to a commit.

**Comment by xrotwang** [comment]
I think that's too implicit. Also: what's the "latest" tag in a git repository? Plus there may be all sorts of tags in a repos - not necessarily all will correspond to a version released on Zenodo.

**Comment by tresoldi** [comment]
Ah, ok, makes sense. Carrying a "release on Zenodo" information in the tag label would be an overkill. I'm regenerating my datasets.

**Comment by xrotwang** [comment]
As @SimonGreenhill said elsewhere: We want people to be explicit in what versions they are using. So I guess it makes sense to force ourselves, too, to be explicit.
