### ISSUE TITLE
LexibankWriter must not always limit tables to objects referenced by forms

### ISSUE THREAD

**Issue by xrotwang** [lexibank/pylexibank#158]
Currently, `LexibankWriter` uconditionally prunes related tables to objects referenced by forms:
https://github.com/lexibank/pylexibank/blob/434fa0890ba15e3f1a3ceb446edee0456b020bd2/src/pylexibank/cldf.py#L87-L90

This prevents simple re-use of `LanguageTable`. So there should be a flag, making this behaviour configurable from the caller.

**Comment by xrotwang** [comment]
This issue is somewhat tricky, since the `CLDFWriter` object is instantiated by `CLDFSpec`. Maybe the use case of a dataset creating two CLDF sets sharing a subset of languages is unusual enough to be somewhat awkward to implement (see https://github.com/cldf-datasets/normansinitic/blob/9ef3c3aca1c83adba02da87bb6aa80d5e712e403/lexibank_normansinitic.py#L68-L73)?

**Comment by LinguList** [comment]
I'd say: yes, it is awkward enough, as even this dataset had unshared languages.

**Comment by xrotwang** [comment]
Workaround seems good enough.
