### ISSUE TITLE
NonSplittingDataset causes Exception when writing FORMS.md

### ISSUE THREAD

**Issue by xrotwang** [lexibank/pylexibank#159]
Since `NonSplittingDataset` is implemented using `FirstFormOnlySpec` - which does not have a docstring - writing `FORMS.md` fails:
```python
  File ".../pylexibank/forms.py", line 98, in as_markdown
    res.extend([line.strip() for line in self.__class__.__doc__.splitlines()])
AttributeError: 'NoneType' object has no attribute 'splitlines'
```

**Comment by LinguList** [comment]
I would suggest to give a deprecation warning to all nonsplitting datasets as well, since we have this covered now by the formspec, which is much more consistent then with the dataset, right?

**Comment by xrotwang** [comment]
Well, no need for a deprecation warning if the functionality isn't usable - due to this bug - at all :)

**Comment by xrotwang** [comment]
So, I'd suggest we simply remove `NonSplittingDataset` and `FirstFormOnlySpec`.

**Comment by LinguList** [comment]
yes, agree!
