### ISSUE TITLE
Best practices for datasets with cognates

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#163]
We should discuss best practices for datasets with cognates.

- Do the lexemes in forms.csv need to have a column 'cognacy' attached? (I think so as this is what people would expect, but this then duplicates info in cognates.csv)

- What fields are necessary in add_cognate?

- can't we just automatically add cognates in `add_form_from...` if the field 'cognacy' is present?

**Comment by xrotwang** [comment]
Hm, I sort of regret adding the `Cognacy` field at all. From my point of view, `Cognacy` is to `cognates.csv` what `Value` is to `Form`: If you want the "good" data, go for the latter, if you want to lookup the data as provided in the source dataset, go for the former.

So `Cognacy` does **not** come with any garantees regarding uniqueness, or even syntax. Stuff of the form `1?` may go into `Cognacy`.

**Comment by SimonGreenhill** [comment]
Ok, closing for now.
