### ISSUE TITLE
Store details/statistics in lexibank.json

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#165]
I'm currently scraping github to get statistics on the datasets, rather than parsing README.md, it would be great if we could store the statistics from README.md in a top level machine-readable form (e.g. lexibank.json)

**Comment by xrotwang** [comment]
We used to do this at some point, I think.

**Comment by SimonGreenhill** [comment]
that's what I thought, but not sure where it went.

**Comment by xrotwang** [comment]
I moved `.transcription-report.json` into`cldf`, because it should be re-generated together with the CLDF. Maybe we could do the same with a `.summary.json`? Or merge both JSON reports?

**Comment by SimonGreenhill** [comment]
Hmm, I agree it makes sense to have it in ./cldf/, but this does mean that we'll be releasing it with the datasets (onto Zenodo etc), so then it's public rather than just a lexibank-specific plumbing.

I think merging them makes sense too?

**Comment by xrotwang** [comment]
The whole repos is archived with zenodo - not only the cldf directory.

Simon J Greenhill <notifications@github.com> schrieb am Do., 19. Dez. 2019,
20:46:

**Comment by SimonGreenhill** [comment]
ok, my objection then has no merit :)

**Comment by SimonGreenhill** [comment]
Decided against.
