### ISSUE TITLE
Should "lexibank.check" raise an Exception if any warnings are issued?

### ISSUE THREAD

**Issue by xrotwang** [lexibank/pylexibank#181]
I think it would be easier to integrate `cldfbench lexibank.check` with `cldf-buildbot` if it returned a non-zero exit status, e.g. by raising an exception, if any warnings have been issued during the checks.

**Comment by xrotwang** [comment]
Ah, just learned that buildbot has a result code [WARNINGS](http://docs.buildbot.net/latest/developer/results.html#buildbot.process.results.WARNINGS) and that we can easily set that via a `ShellCommand`s [decodeRC](http://docs.buildbot.net/latest/manual/configuration/buildsteps.html#shellcommand) argument.

So, I'd propose to return `2` from `lexibank.check` in case any warnings have been issued.

**Comment by xrotwang** [comment]
It may still become a bit of a problem, if many datasets trigger warnings about things that cannot be fixed, e.g. about bookkeeping languoids with no alternative. But I guess, we'll have to see how this pans out in practice.

**Comment by xrotwang** [comment]
I like it!

![Screenshot_2020-03-06 Buildbot](https://user-images.githubusercontent.com/870184/76070676-38724480-5f95-11ea-842d-03a92bc32ba1.png)
![Screenshot_2020-03-06 Buildbot builder lexibank-chenhmongmien build 2](https://user-images.githubusercontent.com/870184/76070678-39a37180-5f95-11ea-811e-4281c066e892.png)

**Comment by SimonGreenhill** [comment]
Oh that’s cool. Everything  done in 2m or so. This is going to be really helpful!

**Comment by xrotwang** [comment]
Looking forward to seeing this with >100 datasets on the server :)

**Comment by xrotwang** [comment]
And I think at [~100 lines of config](https://github.com/cldf/cldf-buildbot/blob/master/config.py), that's still fairly maintainable.

**Comment by SimonGreenhill** [comment]
Just need to make sure we have lots of cores and we can just spawn a worker per dataset :)

**Comment by xrotwang** [comment]
Hitting "build all" in the evening and fixing warnings during the day is probably ok, too, to push out a release within a couple of days :)
