### ISSUE TITLE
Do we need to validate license

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#193]
Currently we just check that metadata.json::license is non-null. However, do we want to make sure it's a valid URL (e.g. "https://creativecommons.org/licenses/by-nc/4.0/") rather than a plain text string (e.g. "CC-BY")?

**Comment by xrotwang** [comment]
We do something in this direction at least, see https://github.com/cldf/cldfbench/blob/9c7d04059d76fe08ddf2f8c148ffba3ae89d7d8f/src/cldfbench/metadata.py#L66-L69

**Comment by SimonGreenhill** [comment]
ok, I'll close this then
