### ISSUE TITLE
Where's the authoritative data?

### ISSUE THREAD

**Issue by xrotwang** [lexibank/pylexibank#2]
We had some discussions before regarding what should be seen as the authoritative data - the CLDF datasets (now in separate repositories) or the SQLite database. I think with the new setup, an answer would be more clear cut:

The separate dataset repositories are the place where data curation happens, with the `cldf` directories as the final output of a curation pipeline (which may or may not be pylexibank powered). All analysis/visualization/query functionality (including `ls`) implemented by pylexibank OTOH should only use the SQLite database (for performance reasons).

This could also simplify the CLI; all functionality dealing with dataset repositories (`download`, `report`, etc.) could be combined into **one** subcommand `curate`, starting an interactive REPL as described [here](https://opensource.com/article/17/5/4-practical-python-libraries), offering things like tab-completion for dataset names. Then there would be one command to selectively load a set of datasets into the SQLite DB, and then (possibly pluggable) commands analyzing this data.

Thoughts?

**Comment by xrotwang** [comment]
Ping @SimonGreenhill @tresoldi @LinguList @chrzyki

**Comment by LinguList** [comment]
I'd strongly support this. Imagine manual curation passes with EDICTOR, you could also reduce the curate command to one that drops from the edited TSV file to CLDF, and people working on the data manually would be able to publish different versions, etc.

**Comment by SimonGreenhill** [comment]
I agree with the authoritative data being the repository, and sqlite as the local database that datasets get installed into. 

How big is glottolog sqlite and conception sqlite? if these could be installed too this would make life much easier (perhaps these could be external databases that get ATTACHed?) 

I'm not a fan of working via REPL -- not scriptable or replicable -- so I'd prefer to also be able to run 'lexibank curate <subcommand>'

**Comment by xrotwang** [comment]
You could still script the curation workflow in python - but not so easily in the shell (although we could add support for both, REPL and CLI).

Regarding replicability, I'd say, with both raw data and CLDF under version control, the "how exactly did we get one from the other" isn't so interesting anymore (there are probably too many moving parts anyway, to ensure full replicability). But it will always be possible to compare raw and CLDF side by side, and to make sure a certain analysis uses a fixed version of data. (And the REPL writes a command history :) )

The nice thing about the REPL is that it becomes a lot easier to provide stuff like auto-completion in a cross-platform way.

**Comment by SimonGreenhill** [comment]
we store file hashes of the CLDF files, right? do these get loaded into SQLITE as well?

**Comment by xrotwang** [comment]
With the CLDF data in git, there's no need for these file hashes anymore. To figure out what's installed, you'd run
```
$ pip freeze | grep lexibank_
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
-e git+https://github.com/lexibank/abvd.git@3fa3516f9404d3ae3aaf7b88aa0726d0c7e3b705#egg=lexibank_abvd
-e git+https://github.com/lexibank/allenbai.git@0d433876b3ed4778a802bcd96bff740d144c50b9#egg=lexibank_allenbai
-e git+https://github.com/lexibank/beidasinitic.git@40942621a3a6f60ccfbd0988e47fb9248245efdd#egg=lexibank_beidasinitic
-e git+https://github.com/lexibank/ids.git@c8a6bfaba5508a95debbb42e87e7a41b82b669b2#egg=lexibank_ids
-e git+https://github.com/lexibank/kraftchadic.git@0b4aed46ec84a66d1529722d09f7e7cd4ed22509#egg=lexibank_kraftchadic
```

**Comment by xrotwang** [comment]
We could put the commit hashes of the dataset repos into SQLite. Should we?

**Comment by SimonGreenhill** [comment]
I can see the SQLIte databases getting archived and shared etc while I think people are less likely to share a version-pinned requirements.txt.  So I think it makes sense to store in database too (if they're not there, then someone will need them. If they are there, then no-one will ever need them).

**Comment by xrotwang** [comment]
ok. added.

**Comment by xrotwang** [comment]
A potential problem just occurred to me: If we really want to push virtualenvs as the way to handle different selections of lexibank datasets on the same machine, a single SQLite database won't cut it anymore. It is already possible to pass a `db=...` option to the commands, but the default is still virtualenv-unaware.

Should we follow [this advice](https://stackoverflow.com/a/1883251) to guess virtualenv-specific default locations or do away with a default altogether?

**Comment by xrotwang** [comment]
Reading the comments on the recommended way to guess virtualenvs make me feel that this is rather hacky and unreliable. So my vote would go to requiring a SQLite db path argument for all `lexibank` commands.

**Comment by chrzyki** [comment]
Agreed, path argument is, in my opinion, preferable.

**Comment by tresoldi** [comment]
Agreed. Maybe we can default to path nonetheless, overridden by a command-line argument?

**Comment by xrotwang** [comment]
@tresoldi that's the current status quo. But the default location `~/.cache/pylexibank/db.sqlite` maybe too opaque? I'm not really sure, what and how big the risc is. Could it happen, that someone works on two different analyses at the same time, using different versions of the same datasets - or at least mostly overlapping datasets? If not, then "multiple lexibank venvs" would be an expert option, and it could be expected that users know and remember to pass in a db option.

OTOH it would be a bummer, if just by replicating some study (e.g. when reviewing) you'd overwrite your own default lexibank db ...

**Comment by chrzyki** [comment]
Having just looked for (and being confused by) the default location, I find it a tad opaque. :) The current working directory wouldn't be an option?

**Comment by xrotwang** [comment]
Yes, I guess `<cwd>/lexibank.sqlite` would be the best option for a default location, given that people are likely to operate in an environment with multiple inputs and outputs.

**Comment by SimonGreenhill** [comment]
Hmm.  I like <cwd>/lexibank.sqlite, but how is python support for [ATTACH](https://www.sqlite.org/lang_attach.html)? 

At the risk of over-engineering: Each dataset could get installed to ~/.cache/pylexibank/db-${dataset}-${version}.sqlite i.e. a unique filename per dataset/version (solving the over writing when reviewing problem), and then pylexibank ATTACHes all the databases required.

(and it's also not sensible ~/.cache/... on OSX, it's stupid ~/Application Support/pylexibank/...)

**Comment by xrotwang** [comment]
I think the "multiple db files + ATTACH" solution is both, over-engineeering and insufficient :)
In this scenario, each database file would have the same set of tables (with only one row in the dataset table). Having to concatenate these tables on query time seems cumbersome; also, there's a hard maximum on the number of databases you can attach: [SQLITE_MAX_ATTACHED](http://www.sqlite.org/limits.html#max_attached), which may be too low for our purposes (the default of 10 certainly is).

**Comment by SimonGreenhill** [comment]
but lexibank totally needs to shard to be webscale for web 2.0!

Ah, I wasn't aware of SQLITE_MAX_ATTACHED. Oh well, nevermind.

**Comment by xrotwang** [comment]
Ok, I guess the CLICS experience has shown that the issue is resolved as proposed in the issue description.
