### ISSUE TITLE
Add check to detect cross-concept cognate sets

### ISSUE THREAD

**Issue by xrotwang** [lexibank/pylexibank#203]
By default, cross-concept cognate sets should be considered an error. Datasets should explicitly declare if they provide such cognate sets, using a suitable flag.

**Comment by LinguList** [comment]
I am against saying that they are by default an error, as this goes against all linguistic practice. It also goes against the most easy way of annotating data. IDs for cognates are global, as we define for CLDF. If IDs cross semantic boundaries, we can specify them positively as being cross-semantic, but we don't need to call this an error.

**Comment by LinguList** [comment]
I would say: it is really the responsibility of lexibank coders to DETECT that cognate sets are encoded locally in the original (which is a problematic in my opinion).

**Comment by LinguList** [comment]
sorry, I just realized: yes this solution would be fine: cross-semantic is marked as such, and CLDF cognate sets are global, so if they cross semantics, this must be licensed, but I would be strongly against allowing the opposite: licensing local cognate IDs.

sorry, took some time to get this right.

**Comment by SimonGreenhill** [comment]
Yes -- so global cognates are default, x-semantic are flagged explicitly in the dataset? e.g. something like: 

```python
class Dataset(BaseDataset):
    dir = Path(__file__).parent
    id = 'blah'
    cognates = 'crosssemantic'
    language_class = Language
```

?

**Comment by SimonGreenhill** [comment]
...and then lexibank.check can raise an error if cognates are cross-semantic and this flag is NOT set?

**Comment by LinguList** [comment]
This would be fine by me, it would also be useful information, e.g., if
somebody wants to test new methods or the like...
