### ISSUE TITLE
Check for missing_data also *after* cleaning forms?

### ISSUE THREAD

**Issue by xrotwang** [lexibank/pylexibank#209]
In [`polyglottaafricana`](https://github.com/lexibank/polyglottaamericana) there are a lot of cases of forms like "? (nénokényi, néṛokényi)". One transparent way to handle these dubious forms would be to just treat them as missing data. With the current `FormSpec` implementation that's not possible. Instead, `?` will end up as the form, even though it may be listed as `missing_data` marker.

We could change this, by comparing forms against `missing_data` at the end of the form cleaning process as well.

Thoughts?

**Comment by tresoldi** [comment]
I also noticed many cases with plural forms, which we probably don't want (the formation seems to be regular, albeit somewhat unexpected in some cases).

Would anyone be mad if I suggest doing some kind of pattern matching only within the context of this dataset? No need for regexes, just simple and stupid `if`s...

**Comment by xrotwang** [comment]
@tresoldi but ignoring the plural forms works with current `FormSpec` functionality via `first_form_only=True`.

**Comment by tresoldi** [comment]
@xrotwang oh right, I was looking at the already split forms in my TRANSCRIPTION.md, my fault.

On your question, my follow-up would be: if after cleaning we do find a form in `missing_data`, what would be the procedure? Would it be up to `pylexibank` to do something by default or to the dataset to decide (potentially manipulating the value)?

**Comment by SimonGreenhill** [comment]
Hmm, I'm happy to check after as well, but I wonder if this is something to handle explicitly at the level of this dataset (i.e. `if form.startswith("?"): continue`)

**Comment by xrotwang** [comment]
Ah, ok. yes, simple `if` seems ok. Or even just listing in `replacements`. It turns out it's just 55 cases ...

**Comment by SimonGreenhill** [comment]
I feel like explicit is better than implicit is a good idea here?

**Comment by xrotwang** [comment]
"Explicit" would probably mean listing in `lexemes.csv` with empty replacement, right?

**Comment by LinguList** [comment]
I support that. If cases are below hundred, it is always better to not apply too much code.

**Comment by SimonGreenhill** [comment]
I think that makes sense -- then we know exactly what's being culled.

**Comment by SimonGreenhill** [comment]
can this be closed?
