### ISSUE TITLE
getEvoBibAsBibtex missing

### ISSUE THREAD

**Issue by tresoldi** [lexibank/pylexibank#21]
The `getEvoBibAsBibtex()` function was removed from `pylexibank.lingpy_util` with the refactoring in [this commit](https://github.com/lexibank/pylexibank/commit/c51d0f01f1703d3ef5e411435acb814067d369a9#diff-5dbe4b3460de377a8a48e21bcad52e6e).

This is breaking some datasets, such as `robinsonap` (maybe I should not have used the command in the first place?). Should we fix the problem in the datasets that use it? I can't find a discussion on the matter, but I assume the function is now deprecated.

**Comment by xrotwang** [comment]
I already fixed it. Will push all datasets now.
