### ISSUE TITLE
Add "how to cite" section in README.md

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#210]
We should add a "how to cite" section to README.md

```markdown
# How to cite

If you use these data please cite:

1. <the original source>

2. <the lexibank dataset>

3. <lexibank itself>
```

It would be nice to automatically add the citations to these three things into the cldf/sources.bib file too.

**Comment by xrotwang** [comment]
While probably a good idea, I don't think this will solve the problem of
people retrieving citation info via the zenodo API - which may deliver
something else than our recommendation.

Simon J Greenhill <notifications@github.com> schrieb am Fr., 10. Apr. 2020,
20:27:

**Comment by LinguList** [comment]
Yes, agree with @xrotwang. The key is to get the zenodo api to a point where we all can be happy with it. As zenodo pulls in github contributors as a default, we have to decide how to prevent that, and how to make sure that all people in contributors.md are listed. We also have to change the titles of our datasets. 

As a recent example, consider [chenhmongmien on zenodo](https://zenodo.org/record/3741500), it uses our old release statement, as this was not updated. But we have changed the year to 2012 long time ago.

So we need to make sure to go through all datasets and keep a clear-cut naming of the dataset, plus authors and the like. 

If it is possible to use the api of zenodo independent of the github integration, this would probably be best, as it would give us all control.

**Comment by LinguList** [comment]
But I am not sure how difficult and how stable this api is (yet they allow to deposit datasets with python alone).

**Comment by xrotwang** [comment]
Adding authors isn't particularly difficult. We can do that
programmatically already.

Johann-Mattis List <notifications@github.com> schrieb am Fr., 10. Apr.
2020, 22:20:

**Comment by LinguList** [comment]
Okay, according to our agreement on the SciData paper, we decided by then to title our datasets upon release as: 

> CLDF dataset derived from AUTHOR's TITLE from YEAR

Title refers to the title we give to a dataset, usually the title of a book, but in shortened form.

If we could also trigger that upon releases this will be set as the default title AND add the authors, which we decide to author a given dataset, this would solve all problems (apart from the fact that we should go back and modify past datasets' metadata on zenodo).

**Comment by LinguList** [comment]
I did not find any templates for making a release on github, but I found that they have [query parameters](https://help.github.com/en/github/administering-a-repository/automation-for-release-forms-with-query-parameters?algolia-query=release#supported-query-parameters) to make a release for a dataset.

What if we just add a `cldfbench github.release` statement that would allow us to release a dataset by opening a URL or providing a URL that one should open to release the data?

One can even fill the "cite the original dataset as" in there, etc.:

e.g., you can open:

```
https://github.com/lexibank/hubercolumbian/releases/new?tag=v2.0.0&title=CLDF%20dataset%20of%20Huber%20and%20Reeds%20Comparative%20Vocabularies%20from%201992&body=cite%20this%20dataset%20as
```

**Comment by LinguList** [comment]
And maybe, we could add a release command to zenodo as well, so we could avoid doing this via the github hooks?

**Comment by xrotwang** [comment]
@SimonGreenhill If we do this (i.e. add a "How to cite" section), I think this should be fairly generic - at least regarding the lexibank dataset - because the DOI of this dataset is not known when the README is put together, to no correct/complete citation can be given. So maybe something like

## How to cite

If you use these data please cite:

1. the original source

> `metadata.json['citation']`

2. the derived lexibank dataset using the DOI of the particular released version on Zenodo you were using.

**Comment by SimonGreenhill** [comment]
generic sounds good, I think it doesn't hurt to add a reminder.

**Comment by xrotwang** [comment]
`cldfbench` already adds a section "Cite the source dataset as ...". So probably we should expand this bit to a full "How to cite" section?

**Comment by xrotwang** [comment]
Closed in favor of https://github.com/cldf/cldfbench/issues/33
