### ISSUE TITLE
Add check that metadata['title'] follows recommended form?

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#213]
Do we want to check if the title follows the [recommended form](https://github.com/lexibank/lexibank/blob/master/CONTRIBUTING.md#titles-for-lexibank-datasets): 

```
  "title": "CLDF dataset derived from AUTHOR's \"SHORTTITLE\" from YEAR."
```

(even superficially like `assert title.startswith("CLDF dataset")`)

**Comment by LinguList** [comment]
Yes, in fact, the check is in chaconcolumbian. If you look at the
"test.py" there.

**Comment by LinguList** [comment]
```

def test_valid_title(cldf_dataset, cldf_logger):
    title = cldf_dataset.metadata_dict['dc:title']
    assert title.startswith('CLDF dataset derived from')
    assert title[-4:].isdigit()

```
