### ISSUE TITLE
Prevent calling glottolog.languoids() in --dev mode of make_cldf

### ISSUE THREAD

**Issue by LinguList** [lexibank/pylexibank#217]
So far, we block calling glottolog languoids() in dev mode upon adding a language. In the report, which is a part of make_cldf, however, report.py line 157 calls languoids to check for bookkeeping languages. For this reason, the main idea of the --dev flag, making it easier during the initial development of a new dataset, is lost, although it was already a great help when working on slow computers, as one can see quickly if a script runs through. A simple fix would be to make the checking for bookkeeping languages to occur in non-dev-mode only. One could even add a statement to the report in dev-mode, that would clearly say that it wasn't done with the full glottolog api.

**Comment by xrotwang** [comment]
see #218
