### ISSUE TITLE
Repeated addition of lexibank community for each makecldf run

### ISSUE THREAD

**Issue by chrzyki** [lexibank/pylexibank#219]
https://github.com/lexibank/pylexibank/blob/a678369afabdf1a723e52cc17d201771208510b4/src/pylexibank/commands/makecldf.py#L40

This creates a 'new' lexibank community metadata entry for each run of `makecldf()`, see for example here: https://github.com/lexibank/allenbai/blob/master/.zenodo.json.

Could we just unlink an existing `.zenodo.json` before writing (or 'updating')?

**Comment by xrotwang** [comment]
I think something along the lines of
```python
[{"identifier": id} for id in sorted(set([r["identifier"] for r in md.get("communities", [])] + ["lexibank"]))
```
would be the best solution.
