### ISSUE TITLE
help for curate interpreter

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#24]
It would be great to have a one-line explanation of the commands that can be listed in 'help'. 

Perhaps the easiest way is to patch `__doc__`:

```
commands['quit'].__doc__ = 'quit: exits lexibank curator'
commands['download'].__doc__ = 'download <dataset>: downloads dataset'
```

...and help can print out `__doc__` if available?

**Comment by xrotwang** [comment]
Yes, documentation needs some work. For me the main question to answer before polishing is: Do the commands right now make sense? I think the only reason for having "analyze" and "report" as separate commands is for performance. Ideally, they should always be run together with "convert" (i.e. "makecldf" :) ).
