### ISSUE TITLE
How to add a repo

### ISSUE THREAD

**Issue by martino-vic** [lexibank/pylexibank#250]
I have a cldf dataset of Wilhelm Streitberg's 1910 Gothic dictionary that I'm using for my own research and I thought it might be worth sharing it here but I can't find any guidelines on how to submit a request

**Comment by LinguList** [comment]
Here, you cannot share it. If you want to make a cldf dataset with cldfbench, we gladly guide you through the process. There are several options to do it in such a way that you can also get credits from it:

1. you make a small publication to some data journal presenting the work, and then coordinating the publication via lexibank and Zenodo with us (we'll help in all regards without claiming authorship)
2. you write a small blog post in our blog computer-assisted language comparison in practice https://calc.hypotheses.org where you also present the data and then do the same archiving process with us

If you want to start, contact us via email and we set up a repository for your dataset and help in testing and checking how everything works. You can also start by making your repository on your github and later transfer, or even leave it completely there, and once it is linked on Zenodo, we add it to our zenodo lexibank community: https://zenodo.org/communities/lexibank

**Comment by martino-vic** [comment]
Ah, thank you so much for the guidance, it would be great to get started, so I will send you an e-mail. I can't find the e-mail of the overarching lexibank project though, should I send it to yours, @LinguList? Thank you so much again for your support, it means a lot to me

**Comment by LinguList** [comment]
Yes, send it to me, I'll forward to other people who may want to help.
