### ISSUE TITLE
document usage of curator

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#26]
Running: 

`lexibank curate grollemundbantu --log-level=DEBUG`

...doesn't display any logging info.

**Comment by xrotwang** [comment]
Due to the way the command line is parsed, the global option `--log-level` must be placed before the `curate` subcommand.

**Comment by SimonGreenhill** [comment]
ok then this should be documented somewhere. I see README.md suggests WORKFLOW.md (doesn't exist). Do we need another file, or can we just have README.md?

**Comment by xrotwang** [comment]
I think just `README.md` should be enough. I'm in the process of preparing a PR which integrates `analyze` and `report` into `makecldf`, so the amount of missing docs will decrease also by axing obsolete functionality.

**Comment by xrotwang** [comment]
Does the position of the `--log-level` option need more documentation than
```
$ lexibank --help
usage: lexibank [-h] [--verbosity VERBOSITY] [--log-level LOG_LEVEL]
                command ...

Main command line interface of the pylexibank package.

positional arguments:
  command               requirements | orthography | load | unload | db | diff
                        | ls | bib | clean | wordlength | coverage | curate
  args

optional arguments:
  -h, --help            show this help message and exit
  --verbosity VERBOSITY
                        increase output verbosity
  --log-level LOG_LEVEL
                        log level [ERROR|WARN|INFO|DEBUG]

Use 'lexibank help <cmd>' to get help about individual commands.
```
?

**Comment by SimonGreenhill** [comment]
no, probably just my laziness ('oh I want to add debug logging' without retyping the rest)

**Comment by xrotwang** [comment]
The OSX shell does support command editing, right? So at least you could get away with just the arrow key :)

**Comment by SimonGreenhill** [comment]
yeah lazy lazy :)
