### ISSUE TITLE
add new command test

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#27]
`pylexibank test dataset` would be easier to remember than `pytest --cldf-metadata=cldf/cldf-metadata.json test.py`

**Comment by xrotwang** [comment]
I think it might be more transparent (at least for people knowing their way around python/pytest) to provide a shortcut via preset options in `setup.cfg`:
```
[tool:pytest]
minversion = 3.6
testpaths = test.py
mock_use_standalone_module = true
addopts =
  --cldf-metadata=cldf/cldf-metadata.json
```

**Comment by xrotwang** [comment]
see e.g. https://github.com/lexibank/marrisonnaga/commit/8ab38b37f54cd4f365d7b19a77e5ca6d04d6313c
