### ISSUE TITLE
lexibank script not running after a year

### ISSUE THREAD

**Issue by martino-vic** [lexibank/pylexibank#270]
In [this repo](https://github.com/martino-vic/gerstnerhungarian) the cldf-conversion worked fine a year ago. I made no changes to it and now the conversion fails. I assume it must have to do something with some dependecies that have changed.

When I create a fresh venv, clone the repo, run `$ pip install -e gerstnerhungarian` and then `$ bash hun.sh`, which contains the line `cldfbench lexibank.makecldf lexibank_gerstnerhungarian.py` I get this error message:
```
bash hun.sh
INFO    running _cmd_makecldf on gerstnerhungarian ...
Traceback (most recent call last):
  File "/home/viktor/Documents/GitHub/venv/bin/cldfbench", line 8, in <module>
    sys.exit(main())
  File "/home/viktor/Documents/GitHub/venv/lib/python3.8/site-packages/cldfbench/__main__.py", line 89, in main
    return args.main(args) or 0
  File "/home/viktor/Documents/GitHub/venv/lib/python3.8/site-packages/pylexibank/commands/makecldf.py", line 24, in run
    with_dataset(args, 'makecldf', dataset=dataset)
  File "/home/viktor/Documents/GitHub/venv/lib/python3.8/site-packages/cldfbench/cli_util.py", line 161, in with_dataset
    res = func(*arg, args)
  File "/home/viktor/Documents/GitHub/venv/lib/python3.8/site-packages/pylexibank/dataset.py", line 218, in _cmd_makecldf
    super()._cmd_makecldf(args)
  File "/home/viktor/Documents/GitHub/venv/lib/python3.8/site-packages/cldfbench/dataset.py", line 208, in _cmd_makecldf
    self.cmd_makecldf(args)
  File "/home/viktor/Documents/GitHub/gerstnerhungarian/./lexibank_gerstnerhungarian.py", line 60, in cmd_makecldf
    idx = "{0}-{1}".format(concept.number, slug(concept.gloss))
  File "/home/viktor/Documents/GitHub/venv/lib/python3.8/site-packages/clldutils/misc.py", line 178, in slug
    res = ''.join(c for c in unicodedata.normalize('NFD', s)
TypeError: normalize() argument 2 must be str, not None

```

Earlier I had problems with line 59 in lexibank_gerstnerhungarian.py, where `self.conceptlists[0].concepts` triggered an error.

Surprsingly, the [tests](https://github.com/martino-vic/gerstnerhungarian/actions/runs/4354309430/jobs/7609447909) are still passing

**Comment by LinguList** [comment]
The error is easy to find, right?

**Comment by LinguList** [comment]
You know how to read a traceback? It shows the error is on your side, not on the lexibank side.

**Comment by xrotwang** [comment]
> Surprsingly, the [tests](https://github.com/martino-vic/gerstnerhungarian/actions/runs/4354309430/jobs/7609447909) are still passing

The [tests](https://github.com/martino-vic/gerstnerhungarian/blob/main/test.py) only check the validity of the generated CLDF - they don't run the whole workflow.

**Comment by martino-vic** [comment]
> > Surprsingly, the [tests](https://github.com/martino-vic/gerstnerhungarian/actions/runs/4354309430/jobs/7609447909) are still passing
> 
> The [tests](https://github.com/martino-vic/gerstnerhungarian/blob/main/test.py) only check the validity of the generated CLDF - they don't run the whole workflow.

Oh, this explains a lot, thank you!

**Comment by martino-vic** [comment]
> The error is easy to find, right?

Hmm, I haven't found it yet

**Comment by martino-vic** [comment]
> You know how to read a traceback? It shows the error is on your side, not on the lexibank side.

Hmm I'm just wondering why the error is on my side, if nothing changed on my side

**Comment by xrotwang** [comment]
You are relying on concept glosses in the concept list being non-empty:
https://github.com/martino-vic/gerstnerhungarian/blob/3c982ec49b6cdca45d592f69e2a32966491687d3/lexibank_gerstnerhungarian.py#L60

If you run the CLDF creation against a different version of Concepticon, this may explain the problem.

**Comment by martino-vic** [comment]
> > Surprsingly, the [tests](https://github.com/martino-vic/gerstnerhungarian/actions/runs/4354309430/jobs/7609447909) are still passing
> 
> The [tests](https://github.com/martino-vic/gerstnerhungarian/blob/main/test.py) only check the validity of the generated CLDF - they don't run the whole workflow.

Just wrote a [config-file](https://github.com/martino-vic/gerstnerhungarian/blob/main/.circleci/config.yml) that runs the whole workflow on [circleci](https://app.circleci.com/pipelines/github/martino-vic/gerstnerhungarian?branch=main), to avoid these kind of errors in the future.
