### ISSUE TITLE
Allow consonant clusters to check tildes

### ISSUE THREAD

**Issue by FredericBlum** [lexibank/pylexibank#279]
In some datasets (e.g. blumpanotacana), we use `∼` for nasalization that is a reflex of nasal consonants of other languages. However, this throws an index error for the consonant check. This can easily be fixed, however, if we change one line in the consonant_clusters.py.

Old:
https://github.com/lexibank/pylexibank/blob/58a2670693d996e5f3638d424ecfa14bbf6d571f/src/pylexibank/commands/consonant_clusters.py#L31

New:

`out = [[]] if sound_names[0].split(" ")[-1] in ["consonant", "cluster", "∼"] else []`

**Comment by xrotwang** [comment]
Fine with me. @LinguList thoughts?
