### ISSUE TITLE
Interactive curation REPL

### ISSUE THREAD

**Issue by xrotwang** [lexibank/pylexibank#3]
Playing a bit with the idea of a REPL for the curation part of pylexibank's functionality, below is what I got. I think this could be quite comfortable - and would also solve the problem of caching Glottolog and Concepticon data: We could get rid of the `Cache` class, and instead load fresh data when starting the curation REPL. For caching,  just leave the REPL running.

```python
from prompt_toolkit import prompt
from prompt_toolkit.history import FileHistory
from prompt_toolkit.auto_suggest import AutoSuggestFromHistory
from prompt_toolkit.completion import Completer, Completion
from fuzzyfinder import fuzzyfinder

commands = ['quit', 'download', 'convert', 'analyze', 'report']
datasets = sorted(['wold', 'ids', 'abvd', 'kraftchadic', 'bowernpny'])


class TheCompleter(Completer):
    def get_completions(self, document, complete_event):
        word_before_cursor = document.get_word_before_cursor(WORD=True)
        words = document.text_before_cursor.split()
        if words and words[0] in commands:
            for ds in fuzzyfinder(word_before_cursor, datasets):
                yield Completion(ds, start_position=-len(word_before_cursor))
        else:  # elif word_before_cursor:
            for c in fuzzyfinder(word_before_cursor, commands):
                yield Completion(c, start_position=-len(word_before_cursor))



user_input = ''
while user_input != 'quit':
    user_input = prompt(u'lexibank-curator> ',
                        history=FileHistory('history.txt'),
                        auto_suggest=AutoSuggestFromHistory(),
                        completer=TheCompleter(),
                        ).strip()
print 'see ya!'
```

**Comment by xrotwang** [comment]
Ping @SimonGreenhill @tresoldi @LinguList @chrzyki

**Comment by tresoldi** [comment]
It does look good, certainly better than my own tools which look like 80's BASIC with a 'Do you confirm?' at the end of each loop. ;)

I'll play with it in the afternoon, I can already think of some new commands to extend id. Maybe we should put this in its own branch, trying to make sure that merging will later be seamless?

**Comment by xrotwang** [comment]
I was about to put it into this repos in the master branch - considering that quite a bit has changed already.

**Comment by xrotwang** [comment]
Just pushed. Note that for this to work, you need to have some datasets installed, e.g.
```
git clone https://github.com/lexibank/baidial.git
cd baidial
pip install -e .
```
