### ISSUE TITLE
Languoid updates in command

### ISSUE THREAD

**Issue by chrzyki** [lexibank/pylexibank#36]
https://github.com/lexibank/pylexibank/blob/aac970f4d2fa9f0d972ce10752b7e63e947751a1/src/pylexibank/commands/misc.py#L232-L237

Should this really be happening within a specific command?

**Comment by xrotwang** [comment]
Ah, no. This command is obsolete and should be removed.

Christoph Rzymski <notifications@github.com> schrieb am Di., 26. Juni 2018,
15:04:

**Comment by chrzyki** [comment]
Removed in https://github.com/lexibank/pylexibank/commit/a4080d5331b5f9489b6414f3ecddb1c3d11b7b39.
