### ISSUE TITLE
Create metadata for ZENODO 

### ISSUE THREAD

**Issue by xrotwang** [lexibank/pylexibank#38]
We should create/update metadata for ZENODO when creating the CLDF dataset. Probably the best way to do this would be a file `.zenodo.json` in the repository, with the relevant fields updated from `metadata.json`.

As a first step towards implementing this, we should add `.zenodo.json` - as these can be imported from ZENODO - for released datasets, to get a clear picture of their format.

**Comment by chrzyki** [comment]
Will have a look at this!

**Comment by xrotwang** [comment]
The `creators` list in `.zenodo.json` could be filled in from [CONTRIBUTORS.md](https://github.com/lexibank/beidasinitic/blob/master/CONTRIBUTORS.md). Ideally, the table in `CONTRIBUTORS.md` would contain ORCIDs.

**Comment by xrotwang** [comment]
Creating metadata for ZENODO in this way is a bit problematic in terms of the publishing workflow, though. Validation errors for the metadata will only turn up **after** the webhook has successfully been run, i.e. after the GitHub release is done.

So if we go this way, we must make sure only valid `.zenodo.json` files are ever created!

**Comment by xrotwang** [comment]
Post-publication metadata editing seems to be the more reliable option here.

**Comment by xrotwang** [comment]
Superseded by #137
