### ISSUE TITLE
Provide more summary statistics

### ISSUE THREAD

**Issue by LinguList** [lexibank/pylexibank#39]
This is my wish list, now that I started enjoying the checks with BIPA etc.:

* average mutual coverage of a wordlist (along [these](http://lingpy.org/news.html#sanity-checks-of-linguistic-data) lines, but there's an update that runs even better)
* concepticon mergers, etc. (I think, there's even a bug now, as it may list 100%, but there are concept sets left unmapped)
* average word list size (per language)

Maybe there's more, but can't think of it by now.

**Comment by xrotwang** [comment]
What you list here are more summary statistics than sanity checks, right? I.e. for none of these we have a threshold which would signal an error?

If so, I'd rename the issue to "provide more summary statistics" or similar.

**Comment by SimonGreenhill** [comment]
* average cognate set set (+- s.d.)

**Comment by SimonGreenhill** [comment]
closing this in favor of specific issues.
