### ISSUE TITLE
Migrate from CLPA to CLTS

### ISSUE THREAD

**Issue by xrotwang** [lexibank/pylexibank#4]
This may be the last remaining major change. But will also require re-processing all datasets.

**Comment by xrotwang** [comment]
@tresoldi @LinguList only assigned you tentatively, since you are the most knowledgeable about these things. We can also figure out in Jena end of April how to split the tasks.

**Comment by LinguList** [comment]
I guess we should be able to look into this...

**Comment by tresoldi** [comment]
Yes, I should probably be the one in charge -- it might help with the multitier project I'm on and might "force" me to finish my model of articulatory features.

**Comment by LinguList** [comment]
We should take this as a starting point for making more fine-grained mappings and tests. These include, in my opinion:

* basic orthoprofile, generated in some way, maybe with lingpy or manually, or even derived from already segmented forms
* for each column "IPA" (or maybe we should call it BIPA), we check whether the sound is attested and convert it to its alias, so t+BAR+s becomes ts, etc.
* if it's an unknown sound, we should use the source-target notation, indicating that the sound is unknown, so A becomes ```A/?``` (or just an empty symbol). 
* if people are not sure as to the bipa-target, they can also use the source-target notation: ```h₂``` becomes ```h₂/ə```

I'd say, this guarantees that we control the segmented output, and we won't have to check it on the actual data.

**Comment by tresoldi** [comment]
The main function that needs work is `src/pylexibank/lingpy_util.py/test_sequence()`, I'm on it.

**Comment by LinguList** [comment]
Okay, excellent, I'll review once ready.

However, if we follow the strategy of testing already at the ortho-profile level, what we need to do is to write a new script testing the BIPA column of orthoprofiles for consistency and replacing the chars that are not good.

**Comment by tresoldi** [comment]
In process at https://github.com/lexibank/pylexibank/pull/22

**Comment by SimonGreenhill** [comment]
Done!
