### ISSUE TITLE
Provide a cookiecutter template for new datasets

### ISSUE THREAD

**Issue by xrotwang** [lexibank/pylexibank#41]
Possibly the simplest way to implement some sort of templated dataset creation would be to offer a lexibank [cookiecutter](https://github.com/audreyr/cookiecutter) template.

**Comment by xrotwang** [comment]
OTOH, the template would provide the wiring between data and pylexibank - so would typically be dependent on a particular pylexibank version. Thus, we may fare better with the template being part of pylexibank.

**Comment by xrotwang** [comment]
Thinking a bit more about this, I guess a simpler approach would suffice - basically a `lexibank template`, 
- iterating over the files in a `dataset_template` directory,
- filling in the templates using `"".format()`,
- copying the rendered templates to an output dir.

**Comment by xrotwang** [comment]
Template content in file names should be marked using `+` instead of curly braces.

**Comment by SimonGreenhill** [comment]
yes -- metadata.json etc might/will change across versions so having it tied to lexibank makes sense.
