### ISSUE TITLE
Update docs and cookbook

### ISSUE THREAD

**Issue by xrotwang** [lexibank/pylexibank#43]
Most of the stuff here https://github.com/clics/clics2/blob/master/cookbook/README.md should rather go to pylexibank/cookbook/README.md

**Comment by SimonGreenhill** [comment]
The old lexibank repository had lots of cookbooks that should be updated: https://github.com/glottobank/lexibank-data/tree/master/cookbook

**Comment by SimonGreenhill** [comment]
Closing this. Open new issues with specific problems.
