### ISSUE TITLE
Ability to specify path to database

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#45]
I'm trying to run lexibank in a venv, with a venv specific database (i.e. I want lexibank.sqlite to have a subset of datasets in it). Is this possible?

**Comment by SimonGreenhill** [comment]
Actually this is solved if the cli can simply give a path to the database e.g. 
```
lexibank --db my.sqlite load
```

**Comment by SimonGreenhill** [comment]
Yes! Thats exactly what I want -- can we get this into pylexibank?

**Comment by LinguList** [comment]
Actually, you know HOW we are doing it there? We just make another venv and a fresh lexibank install, with the list of packages to be installed from there. So you can do this WITHOUT doing anything specific, by just making a new venv (using mkvirtualenv or similar). Then, you just paste the list of [datasets](https://github.com/clics/clics2/blob/master/datasets.txt) with pip, and it's done...

**Comment by xrotwang** [comment]
It should be possible already, no? You create a new virtualenv, install lexibank and a bunch of datasets, then run `lexibank load` - `lexibank.sqlite` in the cwd now should contain only the installed datasets.

**Comment by xrotwang** [comment]
**And** you can pass a `--db=my.sqlite` option to `lexibank`.

**Comment by SimonGreenhill** [comment]
hmm. maybe something's weird with my venv: `lexibank load` doesn't do anything.

**Comment by SimonGreenhill** [comment]
ok, super weird, no lexibank.sqlite appears until I run `lexibank ls` (which shows the datasets installed), and `lexibank load` or `lexibank load dataset` doesn't work, but `lexibank curate` followed by `dbload dataset` does work.

I'll kill my venv, and retry..

**Comment by SimonGreenhill** [comment]
I'll add the --db option to help unless anyone objects?

**Comment by xrotwang** [comment]
Oh, is it hidden? Yes, please add it.

**Comment by xrotwang** [comment]
Ok, I just reproduced what you say. So, `lexibank load` behaves differently from `clics load` (which we should change): It requires dataset IDs as arguments. So yes, `lexibank load` does nothing, `lexibank load <ID>` does. And after loading, `lexibank ls` should show the dataset ID green instead of red :)

**Comment by xrotwang** [comment]
We should align both, the lexibank and clics `load` and `list`/`ls` to mostly do the same thing. Which behaviour do you like better?

**Comment by LinguList** [comment]
I'm pro clics, as I worked more with it. However, the "load" nothing was also a bit difficult to grasp for me the first time, as one expects from earlier behavior that one could load a dataset into the sqlite (also since we can clean the sqlite).

**Comment by xrotwang** [comment]
Yes, I think I'm leaning towards the clics loading behaviour, too; i.e. `lexibank load` will load **all** installed datasets. The `lexibank ls` command may simply need a bit more documentation - or maybe replace the color coding of dataset IDs with a boolean "installed vs. loaded" column.

**Comment by SimonGreenhill** [comment]
yes - intuitively (to me at least) `verb` verb's everything while `verb subset` verbs the subset

**Comment by SimonGreenhill** [comment]
Ahh and I know why nothing happened when I ran `load dataset` -- I'd copied the clics set up which names all the eggs `lexibank_dataset`, and I was just typing `dataset`

**Comment by xrotwang** [comment]
I think the lexibank- prefix is important, though. Because it means we only
have to prevent intra-org name clashes.

Simon J Greenhill <notifications@github.com> schrieb am Do., 2. Aug. 2018,
19:33:

**Comment by SimonGreenhill** [comment]
ok, (main)[https://github.com/lexibank/pylexibank/blob/52570532d9573025b4130b60bb1c07cc5a41f456/src/pylexibank/__main__.py#L112] shows the --db args, but running `--help` gives a generic:

```
usage: lexibank [-h] [--verbosity VERBOSITY] [--log-level LOG_LEVEL]
                command ...

Main command line interface of the pylexibank package.

positional arguments:
  command               requirements | orthography | load | unload | db | diff
                        | ls | bib | clean | wordlength | coverage | curate
  args

optional arguments:
  -h, --help            show this help message and exit
  --verbosity VERBOSITY
                        increase output verbosity
  --log-level LOG_LEVEL
                        log level [ERROR|WARN|INFO|DEBUG]

Use 'lexibank help <cmd>' to get help about individual commands.
```

Must be getting swallowed somehow? Will create a new issue.

**Comment by xrotwang** [comment]
Yes, `help=argparse.SUPPRESS` prevents an option from showing up in the help. I did this for `--db` because in the beginning I though having the DB be put into `appdirs.data` would be best and the user shouldn't even bother where it is. Will change it.

**Comment by xrotwang** [comment]
@SimonGreenhill I just figured out that the `lexibank-` prefix of the dataset IDs in CLICS is sort of accidental - stemming from 
- the fact that pip uses the egg name as directory name when cloning - rather than the repository name
- and that `Dataset` determines its `id` as name of the directory it resides in.

This seems a bit unfortunate, I think, but I'm not sure how a dataset would infer its `id` best.

**Comment by xrotwang** [comment]
Well, after a bit more thinking, I guess it's not too bad, if the `lexibank-` prefix is just stripped off when computing the `id`. We just have to make sure, this convention is well documented. It came into being, because I wanted to prevent any name clashes with other python packages, so lexibank internally, it doesn't have a function.

**Comment by SimonGreenhill** [comment]
hmm, i like the idea of stripping the names when calculating `id` (I'm generally against redundancy and seeing rows of `lexibank-x` is a bit confusing), but I worry about the added complexity and risk of bugs.
