### ISSUE TITLE
remove wordlength function?

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#46]
https://github.com/lexibank/pylexibank/blob/52570532d9573025b4130b60bb1c07cc5a41f456/src/pylexibank/commands/misc.py#L225-L283

**Comment by xrotwang** [comment]
Yes. Probably dysfunctional by now anyway.

Simon J Greenhill <notifications@github.com> schrieb am Do., 2. Aug. 2018,
19:59:

**Comment by SimonGreenhill** [comment]
ok, i'll cull it (and it can be recovered from history if/when Damian needs it)

**Comment by SimonGreenhill** [comment]
and it already removed in https://github.com/lexibank/pylexibank/commit/65ec16a38c4b9f3e9c5fc4b63f2383066ab63e40#diff-cf80d07cccfdc1b88f5343d6a360fa14 I was on a branch (duh). Seems like I should give up work for the day!

**Comment by LinguList** [comment]
And we don't need it: we can use CLICS now to compute it. In fact, we have some code there for it.
