### ISSUE TITLE
bibtex parser strikes if bibtex is not indented

### ISSUE THREAD

**Issue by LinguList** [lexibank/pylexibank#54]
I encountered this problem today:

```
article{key,
author={bla},
year={1000}}
```

This key was not parsed, or let's say: it was more complex, out of a bibliography of more than 90 entries, only about 40 were parsed, here's the file:

[sources.bib.txt](https://github.com/lexibank/pylexibank/files/2340928/sources.bib.txt)

it changed once I used a cleaner and wrote all data in indented form...

**Comment by LinguList** [comment]
addon: I'm talking about ```ds.raw.read_bib()```

**Comment by xrotwang** [comment]
To be honest, I'd be surprised if only indentation was the problem. We are
using pybtex for the parsing,  so this should be quite robust for valid
bibtex.

Johann-Mattis List <notifications@github.com> schrieb am Fr., 31. Aug.
2018, 19:04:

**Comment by LinguList** [comment]
well, jabref parsed it, and wrote it, but left (this seems to be new?) the individual formatting. So didn't solve the problem. Only after I used my custom bibtex handler based on bibtexparser, and wrote it in indented form again, it worked. No idea what happened. But the file I uploaded should replicate this error...
