### ISSUE TITLE
Add functionality to access datasets archived on ZENODO

### ISSUE THREAD

**Issue by xrotwang** [lexibank/pylexibank#56]
It would be good, if functionality were available to access (install?) datasets on ZENODO directly - via DOI or ZENODO ID.

**Comment by SimonGreenhill** [comment]
This should be do-able, but we should think about discoverability then. Where is the 'home' for lexibank datasets (is it still github, and this is just a convenience thing?) Do we need a package index (so packages could live in different homes, but still be installed as wished)

**Comment by xrotwang** [comment]
I see the [lexibank community on ZENODO](https://zenodo.org/communities/lexibank?page=1&size=20) as the catalog (or package index) for lexibank datasets, i.e. as the primary tool for discovery.

**Comment by xrotwang** [comment]
That's an issue for https://github.com/cldf/cldf-zenodo
