### ISSUE TITLE
Add nexus export for lexibank datasets

### ISSUE THREAD

**Issue by xrotwang** [lexibank/pylexibank#60]
As intermediate step in a phylogenetic analysis pipeline we need a conversion of lexibank datasets to nexus as understood by common analysis tools. In a first step this conversion should work on top of the CLDF data of a single dataset, but presumably should be expanded to work on top of a lexibank SQLite database loaded with multiple datasets.

**Comment by xrotwang** [comment]
@SimonGreenhill  Scaffolding is here: https://github.com/lexibank/pylexibank/commit/5adbd4de95d0e2e96309f21a7e610d5be97941dc

**Comment by xrotwang** [comment]
@SimonGreenhill @LinguList this conversion may also use `lingpy.convert.strings.write_nexus`. But I guess, we should decide at the hackathon whether we want to add conversion to `lingpy.Wordlist` to lexibank datasets, or the other way round - add initialization of a wordlist from CLDF to `lingpy`.

**Comment by LinguList** [comment]
I guess, the best would be a mostly generic code that takes, say, a list of languages, and some dictionary with word forms and cognate sets, from which the data would then be computed. This would allow to plug the system into lingpy, or to even use lingpy. If we have to convert from lingpy to CLDF in the future and then form cldf to nexus, this would be a bit tedious, so I'd like to have the possibility to do the conversion both from cldf to nexus and from within lingpy without exporting officially to cldf. With a generic function (that would just require a few tweaks to lingpy.convert.strings.write_nexus, which could then be placed whereever we want), this should be possible, right?

**Comment by xrotwang** [comment]
Well, CLDF (or it's python representation, the `pycldf.Wordlist` object) is supposed to be exactly this "generic" object. That's even more important when additional information is involved, e.g. borrowings, or different binarization algorithms. Would these be tagged on to generic python data structures, or rather to well-defined CLDF components/properties?

**Comment by xrotwang** [comment]
To me, one of the main advantages of CLDF is that a function accepting a `cldf_dataset` as single argument is basically already well documented - as opposed to `def write_nexus(languages, word_forms, cognate_sets)`.

**Comment by xrotwang** [comment]
I should add that in python code - like `lingpy` - this would not necessarily mean writing out CLDF before you can use any CLDF methods, but only creating a `pycldf.Dataset` object; just like you would create an `ete3.Tree` or a `networkx.Graph` before using any of the methods defined for these objects.

**Comment by LinguList** [comment]
Yes, the only problem for me would be, and here we are facing problems of different stages of development, that right now, LingPy can create

* nexus from partial cognates
* nexus from full cognates
* nexus without borrowings
* nexus with borrowings
* nexus from cross-semantic cognates 
* nexus from cross-semantic partial 

and three different types of distances. 

The question I'm asking myself is: if I do my little tools of editing things and tweaking with new software pieces for development reasons, should I run them through CLDF in the future (which is tedious at the moment, as many experimental things are not yet in the format), or could I use some flexible-enough cldf_wordlist lingpy-internally? This would require, for example, that the cldf_wordlist has additional columns with values that would not be officially supported by cldf, etc.

I'd also be curious regarding our aims for functionality: do we want to support all of the formats I mentioned above, or would we make some pre-selection?

**Comment by xrotwang** [comment]
I guess for "little tools for development" you can do whatever - just have an eye towards CLDF compatibility. But when it comes to publication-ready stuff, i.e. you'd have to write documentation or you are using the tools in a paper and would like to have it included in a proper release of a package, I think the interface should be CLDF.

With this in mind, I think all nexus variants you mention would be in scope for the CLDF-to-nexus functionality. Regarding distance matrices, we may want to think whether it's worth specifying these in CLDF. It could be done ad-hoc, with a custom table right now: Basically a table with two language reference columns and the distance in a third column. Maybe such a setup could be accounted for in the nexus conversion if the name of the table and the name of the column storing the distance is passed as argument ...

**Comment by LinguList** [comment]
If we decide to add distance matrices in CLDF, we'll have more showcases for linguistic data, that could be included among cldf-datasets. For examples, see here:

* https://github.com/digling/cddb/blob/master/datasets/Tang2007/raw/Tang2007-table-a1.csv

and here

* https://github.com/digling/cddb/blob/master/datasets/Tang2009/raw/Tang2009-table-3.csv

These are two texts (and there are more of this kind), where authors share the distances, to indicate, for example, mutual intelligibility. It's not that all people would be interested in the data, but I find it interesting to store theses digitally as well. 

If we then also add trees in newick format as a possibility to CLDF, we could even provide a more principled access for the data than is done in mulittree and other projects. And again, we could TEST this feature by adding it to cldf-datasets.

**Comment by xrotwang** [comment]
So `LanguageDIstanceTable` would be a component with columns `From_language`, `To_Language`, `Value`? Or is this too specific?

**Comment by LinguList** [comment]
> So LanguageDIstanceTable would be a component with columns From_language, To_Language, Value? Or is this too specific?

Yes, this would be cool, as it would allow us to also add asymmetric distances (and we're working on methods for their assessments in dialect mutual intelligibility).

**Comment by xrotwang** [comment]
Seems well-defined enough to be added for prototyping. Would be also a nice example of enhancing CLDF datasets: An algorithm allows you to compute distances, which are then added back into the CLDF datasets. Yet another algorithm computes a tree from these distances - which again is added to the dataset.

**Comment by LinguList** [comment]
I'd really like this, specifically, since we have neighbor-joining and distance methods already in lingpy, and making them generic should not be that difficult (so they could either live somewhere else, or we'd pull in lingpy for this task).

**Comment by xrotwang** [comment]
As an example, one could turn Gerhard's world tree paper into a CLDF Wordlist + DistanceTable + Phylogeny

**Comment by LinguList** [comment]
Yes, and I could finally add the distance matrices, which I typed off, somewhere. I'd actually say: we need the source as well, so that I could add from which page in a book the distances are taken, so that I could have several distance matrices in the same cldf-dataset, or would that be too much? They often list more than just one distance matrix in those kind of papers...

**Comment by LinguList** [comment]
BTW:  breaking it down, I see nexus conversion as having the following different parameters:

param | type | note 
--- | --- | --- 
exclude-singletons | bool | some analyses don't require the inclusion of singletons, so this should be possible 
format | "splitstree", "beast", "beast-words", "mrbayes", "traitlab" | maybe more, it's a pain in the neck
loans | "include", "exclude", "singletons" | exclude and singletons would be different, as "singletons" means, they'd be listed as singleton cognates, and not removed

For partial cognates, the handling would not be specific, assuming that we have the list of cognates there, so no extra-treatment. Furthermore, for cross-semantic etc. cognates, we have the rule that cognate sets are global, which includes local cognates as well, so it's the user's responsibility to make the cognates global, if they aren't.

**Comment by xrotwang** [comment]
Adding a `Source` column to any CLDF table transparently is already possible. The "multiple distances" issue is trickier, though. We may either allow multiple tables of the same component type (which isn't the case yet), or we'd put all distance data in the same table and distinguish it using another column.

**Comment by xrotwang** [comment]
Ok, factoring in what @SimonGreenhill says, this turns more into adding support for "parameters of two languages". So distances would just be a special case of functions operating on pairs of languages. So maybe, all we need is a generalized "ValueTable"?

**Comment by xrotwang** [comment]
Let's move the discussion over here: https://github.com/cldf/cldf/issues/88

**Comment by SimonGreenhill** [comment]
It seems to me that a conversion to nexus belongs in cldf (=pycldf) as it's not just functionality needed for lexibank but all cldf files with cognates? Would it make more sense to have a cldf-to-nexus package?

**Comment by xrotwang** [comment]
Yes, as far as I can see, there's nothing lexibank specific in the way we handle cognates - it's plain CLDF Wordlists with cognates. Putting this functionality in a separate package would make sense, too. Question is how to slice and dice it: Is it more useful to have a package per output format (e.g. `cldf2nexus`) or per CLDF module (e.g. `cldf_wordlist_util`)? I guess the former makes more immediate sense.

**Comment by xrotwang** [comment]
Another desideratum I'd have is: We should make functionality like binarization of data (e.g. cognate sets or multistate features in StructureDatasets) pluggable, and thus reusable in more than one `cldf2...` package.

**Comment by SimonGreenhill** [comment]
This probably better lives in an addon package to `pycldf`. I think pycldf-nexus makes sense.

**Comment by SimonGreenhill** [comment]
closing as out of scope for now.
