### ISSUE TITLE
Problems with alignments with recent lingpy

### ISSUE THREAD

**Issue by tresoldi** [lexibank/pylexibank#62]
Due to some changes in lingpy during the last months, most of the alignments in lexibank do not seem to work anymore.

There are actually two problems:

* Due to the new `lingpy/basic/wordlist.py:480`, the `cogid` must be something that can be cast to an integer; as such, standard CLDF ids such as `above-14` (the first one in Bowern's Pama-Nyungan dataset, `bowernpny`) will throw an exception `ValueError: invalid literal for int() with base 10: 'above-14'`.

* The problem above can be circumvented by making sure that all cognate ids can be cast to an integer (such as in the `renumber()` method of `WordList`, or by hand in CLDF stuff -- or can we call the internal wl?). Still, this is going to throw a different error, from `pylexibank/lingpy_util.py:106`, as `pylexibank` will try to `split()` the alignment, which is not a string anymore but a basic type (exception `AttributeError: '_strings' object has no attribute 'split'`).

**Comment by xrotwang** [comment]
Ok, just confirmed the problem still exists. Working on a fix (in bowernpny).

**Comment by tresoldi** [comment]
It is solved for `lierberherrkhobwa` but not `bowernpny`.

**Comment by tresoldi** [comment]
I'll push lieberherr meanwhile, as it is working and we need it for the MIT chapter.

**Comment by xrotwang** [comment]
But isn't this a bug in lingpy? In [this line](https://github.com/lingpy/lingpy/blob/1f38c890538d6facbe7e1346fa583f8618fb9faa/lingpy/align/sca.py#L626), is it correct to force `modify_ref=int`, if it is possible to pass in `modify_ref` in `__init__`?

**Comment by LinguList** [comment]
It's something that is not nice in lingpy, I'd say.

**Comment by LinguList** [comment]
This is an old behavior, that was needed to handle old wordlists with negative integers, indicating borrowed items, as given in starling. 

The typical data-type, in lingpy.basictypes is `lingpy.basictypes.ints` for partial cognates, and simply "integer" for normal cognates, although nothing would actually prevent us from also allowing to use strings.

**Comment by xrotwang** [comment]
Ok, I remember the old requirement of `int` cogids. I guess the `modify_ref` confused me. I think I can force integer cogids in `bowernpny`, but how do you signal **no cogid**? `None` will throw an error. Does `0` have this semantics?

**Comment by xrotwang** [comment]
I fixed this for bowernpny. Using integer cognate set IDs should be feasible in most/all cases, so closing.
