### ISSUE TITLE
prompt_toolkit~=1.0 potentially problematic?

### ISSUE THREAD

**Issue by chrzyki** [lexibank/pylexibank#63]
We have `prompt_toolkit~=1.0` in `setup.py`, this clashes, for example, with `ipython` and `jupyter`, both of which require >=2.0.0 (but <2.1.0). Since both of these are common neighbours in virtual environments harbouring Lexibank data, this is potentially problematic (or at least annoying).

**Comment by xrotwang** [comment]
Yes, that's bad. UI is bad. Even if it is just a bit of repl comfort.
Any ideas how to deal with this? Probably, this is only needed for the
curation repl. So maybe it should be only imported upon use?

Am Di., 29. Jan. 2019, 17:34 hat Christoph Rzymski <notifications@github.com>
geschrieben:

**Comment by chrzyki** [comment]
Agreed. Since this is, as far as I can tell, only being used for the REPL, just import for the REPL. :)

**Comment by tresoldi** [comment]
I have been dealing with this for a long time; short story, no ipython on my lexibank virtualenv.

I remember checking prompt_toolkit and the pylexibank code, changes should hopefully be minimum in order to move to the current release.

**Comment by xrotwang** [comment]
Just upgraded to `prompt_toolkit==2.0.8` and everything still seems to work - tests pass, the curation repl seems to work. As far as I can tell, we could just drop the `~=1.0` qualifier - or require `>=2.0` right away.

**Comment by xrotwang** [comment]
@chrzyki @tresoldi could you check whether this works the same on your systems?

**Comment by chrzyki** [comment]
Can confirm, everything seems to be working fine with `prompt_toolkit==2.0.8`, tested: tests, REPL, REPL for different commands (`makecldf` etc.).
