### ISSUE TITLE
User context-based profiles as a default

### ISSUE THREAD

**Issue by LinguList** [lexibank/pylexibank#70]
I tried to manipulate tokenization by modifying the "tokenize" attribute, of the dataset.Dataset, until I realized, that this is the cldf.Dataset, which only has this attribute, so the only way to modify this, was to add this hack:

https://github.com/lexibank/chenhmongmien/blob/dd1a991364462253af376482ac9262840ce5571a/lexibank_chenhmongmien.py#L84-L87

We need a standard way to handle this, especially since other datasets, like yanglalo use different (similarly ad-hoc) strategies here.

**Comment by LinguList** [comment]
Here the code I now use (see how I overwrite the self.cldf.tokenize, which we should rather modify on another level, as far as I think):

```
        with self.cldf as ds:
            self.cldf.tokenize = lambda x, y: self.tokenizer(x, '^'+y+'$')

for concept in self.concepts:
```

**Comment by SimonGreenhill** [comment]
What's the issue -- you've overridden the base tokenizer [here](https://github.com/lexibank/chenhmongmien/blob/dd1a991364462253af376482ac9262840ce5571a/lexibank_chenhmongmien.py#L66)? is this to workaround the lazyproperty?

**Comment by LinguList** [comment]
The problem is, that the tokenizer is not a part of self, but of self.cldf, so I need to overwrite a class in a class, using lambda. As we want to have some freedom to overwrite tokenizer, it is not optimal that tokenizer is first part of self, and then of self.cldf.

**Comment by SimonGreenhill** [comment]
ah, I get it now. That is ugly :/

**Comment by xrotwang** [comment]
I think the cleanest way to handle this would be overriding `dataset.Dataset.tokenizer`:
```python
    @lazyproperty
    def tokenizer(self):
        tokenizer = Tokenizer(
            profile=Profile.from_file(str(self.dir / 'etc' / 'orthography.tsv'), form='NFC'),
            errors_replace=lambda c: '<{0}>'.format(c)
        )
        def _tokenizer(item, string, **kw):
            kw.setdefault("column", "IPA")
            kw.setdefault("separator", " + ")
            return tokenizer(unicodedata.normalize('NFC', '^' + string + '$'), **kw).split()
        return _tokenizer
```
This way, you get full control. We may provide a shortcut for the path to the orthography profile. But otherwise, I don't thin this is too ugly.

**Comment by LinguList** [comment]
Follow up on our discussion, easiest workaround is: make context-profile DEFAULT, and check for each profile in lexibank if it has `^` with IPA `NULL` and `$` with IPA `NULL`, otherwise add it.
