### ISSUE TITLE
Generic tests for Dataset?

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#72]
Hi all,

Just came across an error in a lexibank dataset because it didn't have a `Dataset.id` property. The tests on the dataset still passed, because things like they look at the CLDF. 

However, it would be nice if the test command could look for simple well-formedness aspects of Dataset, which would be run automatically along with the dataset defined tests.

**Comment by xrotwang** [comment]
Ok. We could add that for lexibank datasets. The current setup simply uses `pytest-cldf`, i.e. a plugin that only looks at the CLDF dataset and runs `cldf validate` on it. Guess that would mean a `pytest-lexibank` plugin.

**Comment by SimonGreenhill** [comment]
Hmm, is this adding unnecessary complexity?

**Comment by xrotwang** [comment]
Dunno. I agree that it's somewhat problematic that the CLDF data and the code, supposedly used to create it, may be out of synch. And maybe the dual function of `Dataset` to write **and** read the data in `cldf/` is also problematic.

So, I guess we should add checks for the data reading bit of `Dataset`, because otherwise we may end up with lexibank datasets which do not function within lexibank :)

**Comment by SimonGreenhill** [comment]
I think we need to do something to keep the horde of datasets we have updated with lexibank/concepticon/glottolog/clts/etc/etc. We've got ~40 already, so that's painful to do manually.

Do we need to think about something like a build/CI solution that polls the lexibank organisation, clones everything, and rebuilds the CLDF. This could run download/makecldf/test, and any failures or diffs on that route get flagged for someone to check?

**Comment by xrotwang** [comment]
Yes, I think we could set up something like this easily enough. I'd poll the ZENODO lexibank community, though - which can be done via OAI-PMH.

**Comment by LinguList** [comment]
On the issue of the two-face of lexibank.Dataset: I have had good experience with using lexibank from within python in two or three projects, so this functionality of accessing the data from python, but also the repo, is crucial in my opinion. Separating it would probably be useful especially before I start adding more code that relies on that functionality. But for the time being, there's only hantganbangime and sagartst.

**Comment by SimonGreenhill** [comment]
Closing this in favor of #113
