### ISSUE TITLE
Improve summary on number of cognate sets of a dataset

### ISSUE THREAD

**Issue by Bibiko** [lexibank/pylexibank#73]
Now it gives the number of cognate sets which have more than one member. It could be confusing thus output this info and/or add the total number.

**Comment by LinguList** [comment]
We could even add the average size of cognate sets, or the *density* (see [here](http://dx.doi.org/10.1371/journal.pone.0170046)).

**Comment by SimonGreenhill** [comment]
I think @LinguList  means 'diversity':

> The diversity index given in the last column of the table is calculated by dividing the difference between cognate sets and meanings with the difference between words and meanings [19]. This score, which ranges between 0 and 1, indicates whether large numbers of words in a given dataset are unrelated (high index) or are cognate (low index). As can be seen from the diversity indices listed in the table, our test sets have varying degrees of diversity, ranging from 0.07 (Romance, Saenko, 2015) to 0.57 (Uralic).
