### ISSUE TITLE
Make makecldf take optional arguments for Glottolog/Concepticon release tags

### ISSUE THREAD

**Issue by chrzyki** [lexibank/pylexibank#78]
For writing papers, testing, debugging, etc. it would be very helpful if you could supply `lexibank makecldf xyz` with optional arguments for specifying which Glottolog and/or Concepticon release tag to use. For example, I would like to build the CLDF of a lexibank data set with Concepticon 1.1.0:

```
lexibank --concepticon=1.1.0 makecldf halenepal
```

and I would like to compare how the mappings (and subsequently the CLDF output) changed in comparison to Concepticon 1.2.0:

```
lexibank --concepticon=1.2.0 makecldf halenepal
```

This would also make mixing different versions very neat:

```
lexibank --concepticon=1.1.0 --glottolog=3.4 makecldf halenepal
```

With this, one could very neatly and automatically create nice plots, graphics, etc. showing how mappings and CLDF output get (ideally!) better with new versions of the reference catalogs.

**Comment by chrzyki** [comment]
Potentially with a different syntax (using the `repos` argument and maybe something like `path@VERSION`.

**Comment by tresoldi** [comment]
Agreed with @chrzyki , this would be very useful.

**Comment by SimonGreenhill** [comment]
This might be something for cldfbench?

**Comment by xrotwang** [comment]
True - although Concepticon is somewhat `Wordlist` specific ...

**Comment by LinguList** [comment]
Yet if we include pyclts as a standard also for phoneme inventory data in cldfbench/cldf 1.2, we would simply say that standard reference catalogs are supported by version, right? And these would be concepticon, glottolog, and clts ?

**Comment by xrotwang** [comment]
Yes, that makes sense. And we have stuff like WALS' "Hand and Arm", where examples could be liked to Concepticon even though the whole dataset is a `StructureDataset`.

**Comment by xrotwang** [comment]
closed in favor of https://github.com/cldf/cldfbench/issues/4

**Comment by SimonGreenhill** [comment]
yes, and it's not inconceivable that we couldn't create new reference catalogs in future too.
