### ISSUE TITLE
Moving forward to PY3, remove PY2 functionality from template

### ISSUE THREAD

**Issue by chrzyki** [lexibank/pylexibank#79]
In the very near future, we'd like to have any PY2 extras removed, for example:

https://github.com/lexibank/pylexibank/blob/be6fb454628cc5e7f003ac2f0ef8bcf438680725/src/pylexibank/dataset_template/setup.py_tmpl#L6-L8

**Comment by SimonGreenhill** [comment]
oops, I did that in https://github.com/lexibank/pylexibank/commit/c28e7f122f20de1232623dd7003cb5b01535e581
