### ISSUE TITLE
Negative cognate diversity in reportings, README updates

### ISSUE THREAD

**Issue by chrzyki** [lexibank/pylexibank#83]
Unfortunately, this calculation here https://github.com/lexibank/pylexibank/pull/82/files causes large negative numerators in the fraction for data sets with `cids` but 0 `num_cognates`. The result is a negative cognate diversity for data sets with no added cognacy, e.g.

```
$ lexibank makecldf sohartmannchin
- **Cognacy:** 0 cognates in 0 cognate sets (0 singletons)
- **Cognate Diversity:** -0.15
```

```
$ lexibank makecldf diacl
- **Cognacy:** 0 cognates in 0 cognate sets (0 singletons)
- **Cognate Diversity:** -0.01
```

Is this intended?

**Comment by LinguList** [comment]
Nope, it should not be intended, it should in fact only count those cases where a word has a cognate. If there are no cognates, it should yield NONE. In general, I'd advocate that the cldf cognacy things be only shown if there are cognates, same for segments, as this will also help to rate a dataset visually. Would this be trivial to do?

**Comment by xrotwang** [comment]
Well, at this point nothing is trivial anymore because everything requires a new release - although this one would probably count as bug fix.
Do you want to take a stab @chrzyki ?

**Comment by chrzyki** [comment]
Yep

**Comment by xrotwang** [comment]
@chrzyki oh, sorry, already started. will push my state in 5 mins, so could test?

**Comment by chrzyki** [comment]
Meh, this one time I was almost faster than you. Go ahead. :) Will test. Your solution is probably also prettier than mine.

**Comment by xrotwang** [comment]
As pretty as if statements come :)

**Comment by SimonGreenhill** [comment]
ahh, good catch. Thanks all.
