### ISSUE TITLE
Add computed phoneme inventory visualisation

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#84]
One of the cool things we discussed was computing the phoneme inventory with frequencies into an IPA table. This might be nice in the dataset report?

**Comment by LinguList** [comment]
Yep, problem would only be the IPA table, but one could start out with the one from edictor: [here](http://edictor.digling.org/plugouts/ipa_chart.html?doculect=German&sound_list=a%2Cau%2Cai%2Ca%CB%90%2Ca%CB%90%C9%99%2Cb%2Cd%2Ce%CB%90%2Ce%CB%90%C9%99%2Cf%2Ch%2Ci%CB%90%2Cj%2Ck%2Cl%2Cm%2Cn%2Co%CB%90%2Cpf%2Cp%2Cr%2Cs%2Cts%2Ct%2Cu%CB%90%2Cv%2Cx%2Cy%CB%90%2Cz%2C%C3%B8%CB%90%2C%C5%8B%2C%C9%94%2C%C9%94y%C9%99%2C%C9%94y%2C%C9%99%2C%C9%9B%2C%C9%A1%2C%C9%AA%2C%CA%83%2C%CA%8A%2C%CA%8F). It runs from javascript, could be further modified, and fills in slots that are occupied, and leaves out slots with nothing.

**Comment by SimonGreenhill** [comment]
Actually, I think this would make a nice paper. Let's discuss later.
