### ISSUE TITLE
Concepticon sanity checks during makecldf

### ISSUE THREAD

**Issue by chrzyki** [lexibank/pylexibank#91]
It'd be beneficial to have more sanity checks during `makecldf` for Concepticon-related things, akin to what is done in `pyconcepticon` with `check_new()` and the likes. See also this discussion here: https://github.com/clics/pyclics/pull/6.

**Comment by chrzyki** [comment]
Neatly illustrated here: https://github.com/concepticon/concepticon-data/issues/428. The `CONCEPTICON_GLOSS` column in `concepts.csv` is not checked for its content and thus may contain any string. Accordingly, there is also no check for a match between `CONCEPTICON_GLOSS` and `CONCEPTICON_ID`, i.e. whether the gloss matches the id.

**Comment by xrotwang** [comment]
I'm a bit on the fence. I'm sure such checks would be good, but they will also come with more code. So while the checks may help, maybe even more important is some documentation: `CONCEPTICON_GLOSS` in `concepts.csv` is only meant as a help for visual cross checking. And even if it makes it into the CLDF dataset, it should always be the `CONCEPTICON_ID` that is taken as authoritative.

**Comment by chrzyki** [comment]
What about having pyconcepticon as a dependency and just treating a concepts.tsv as 'new concept list', checking it with pyconcepticon's code during the CLDFication? Just a little bit of additional code. :)

On 4 Jul 2019 17:46, Robert Forkel <notifications@github.com> wrote:

I'm a bit on the fence. I'm sure such checks would be good, but they will also come with more code. So while the checks may help, maybe even more important is some documentation: CONCEPTICON_GLOSS in concepts.csv is only meant as a help for visual cross checking. And even if it makes it into the CLDF dataset, it should always be the CONCEPTICON_ID that is taken as authoritative.

**Comment by xrotwang** [comment]
That actually sounds pretty good.

Christoph Rzymski <notifications@github.com> schrieb am Do., 4. Juli 2019,
18:58:

> What about having pyconcepticon as a dependency and just treating a
> concepts.tsv as 'new concept list', checking it with pyconcepticon's code
> during the CLDFication? Just a little bit of additional code. :)
>

**Comment by LinguList** [comment]
Yes, agree.

**Comment by LinguList** [comment]
Or wait: We have in fact been there, and one thing that I find annoying is that treating a concept list in pylexibank as a new concept list is different in many regards, as we use comma-separated mostly, we do not need the lenghty and visually not appealing concepticon-ids which are also difficult to produce for contributors, etc., so this would also require (but I would welcome it) a certain degree of refinement of the pyconcepticon code, which is now quite difficult to apply, e.g., to compare concept list, and for [my toy example](https://calc.hypotheses.org/1933) I could not use two lexibank lists directly.

**Comment by LinguList** [comment]
So 

1. do not underestimate the degree to which this will force us to revise all lexibank datasets, and
2. be careful of concepticon's unfavorable rigorosity when checking concept lists, which is useful internally, but very difficult to cope with if you want to use it to compare or create new conceptlists

**Comment by chrzyki** [comment]
Thanks for the pointers! I'll have a look at this and will see whether it is feasible.

**Comment by SimonGreenhill** [comment]
would this be better implemented as a check command to see if Concepticon_ID and Concepticon_Gloss are the same as those in concepticon?

**Comment by SimonGreenhill** [comment]
@chrzyki  -- can you look into this one please?

**Comment by chrzyki** [comment]
Yepp

**Comment by chrzyki** [comment]
Coming back to this: An `attr.s` validator for `pyconcepticon` during the creation of `Concept()` instances ([here](https://github.com/concepticon/pyconcepticon/blob/5886de566efde28ac98d7f56d9a81c78146130b1/src/pyconcepticon/models.py#L175)) is probably not feasible because this would need access to a properly instantiated `Concepticon()` API.

I'm not entirely sure if a separate check command is good since we've got a bit of command creep with a lot of the CLI tools.

Would this be something we could just check during the call of `cmd_makecldf()` since this needs a `Concepticon` anyway? Then it is just a case of checking gloss/id combinations against whatever was specified with `--concepticon` (or `catconfig`)?

**Comment by xrotwang** [comment]
So I guess the minimal desideratum here is a consistency check for `CONCEPTICON_ID` and `CONCEPTICON_GLOSS`, right? For this, I'd agree with @chrzyki that this should be done right away in during `cmd_makecldf` - presumably in `LexibankWriter.add_concept`.
