### ISSUE TITLE
Better description of the computing environment

### ISSUE THREAD

**Issue by xrotwang** [lexibank/pylexibank#93]
We should switch to describing the computing/data environment using the `prov` vocabulary, rather than an `environment` key in `notes`. This is how we do it for grambank:
```python
    def describe_repos(r, org='glottobank'):
        return OrderedDict([
            ('dc:title', '{0}/{1}'.format(org, r.name)),
            ('dc:description', git_describe(r))])

    dataset.tablegroup.common_props['prov:wasDerivedFrom'] = [
        describe_repos(api.repos),
        describe_repos(glottolog.api.repos, org='clld'),
        describe_repos(wiki)
    ]
    dataset.tablegroup.common_props['prov:wasGeneratedBy'] = describe_repos(
        Path(__file__).parent.parent.parent)
```

**Comment by xrotwang** [comment]
We also need a way to keep track of evolving standards such as this - possibly via a "FAQ" page on https://cldf.clld.org

**Comment by xrotwang** [comment]
Should be done with new pycldf API: https://github.com/cldf/pycldf/blob/6b9ec07aa5130fb1df8f40fef0f4bb955e8aea3c/src/pycldf/dataset.py#L120-L141

**Comment by SimonGreenhill** [comment]
This is done, right?
