### ISSUE TITLE
sanity checks for segmented data

### ISSUE THREAD

**Issue by LinguList** [lexibank/pylexibank#94]
I started drafting a quick check function that can be called as:

```
lexibank check_profile DATASET
```

This is much faster than running the whole workflow, as it will take the value `Form` in `forms.csv`. 

The checks that should be done are (check marks in my implementation, not yet pushed):

- [x] bipa-compability
- [ ] check for duplicated morpheme separator (`+ +`), they should not occur
- [ ] check for initial or final morpheme seps (`+ b l a`) also not allowed
- [ ] zero length output

It could be further expanded and re-cycled for our phonotactic output.

**Comment by SimonGreenhill** [comment]
[] zero-length items

**Comment by LinguList** [comment]
closing now, new command is:

```
lexibank check-profile dataset
```
