### ISSUE TITLE
lexibank available datasets

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#96]
Make a command ("available"?) to read the [Zenodo community](https://zenodo.org/communities/lexibank/) and display all released datasets. Zenodo publishes [OAI-PMH](https://zenodo.org/oai2d?verb=ListRecords&set=user-lexibank&metadataPrefix=oai_dc) which can be harvested.

**Comment by SimonGreenhill** [comment]
c.f. https://github.com/lexibank/pylexibank/issues/56

**Comment by xrotwang** [comment]
We also have CLDF structuredatasets and dictionaries on zenodo, so the
underlying functionality should be somewhat generic and probably
implemented in a cldf-zenodo package. What lexibank adds is mostly the
"install" aspect.

Simon J Greenhill <notifications@github.com> schrieb am So., 7. Juli 2019,
09:24:

**Comment by SimonGreenhill** [comment]
Closing this as nonessential.
